const emotions = {
  怒: { type: '立场型', purpose: '建立人设、替用户说话', advice: '亮态度、划边界、替用户说话', frequency: '每周 1–2 条' },
  喜: { type: '结果型', purpose: '晒成果、给希望', advice: '晒战绩、晒学员案例，给希望', frequency: '每周 1 条' },
  哀: { type: '故事型', purpose: '拉信任、讲经历', advice: '讲转折、讲真实经历，让人看见你的来路', frequency: '每两周 1 条' },
  惧: { type: '痛点型', purpose: '制造紧迫感、引流', advice: '点出风险，但不要持续制造焦虑', frequency: '发售前集中用' },
  爱: { type: '陪伴型', purpose: '拉近距离、社群维护', advice: '多回应、多分享幕后，让用户感到被接住', frequency: '每周 1 条' },
  恶: { type: '筛选型', purpose: '建立高端感、筛选客户', advice: '说清楚不服务谁，建立边界与专业感', frequency: '发售前集中用' },
  欲: { type: '向往型', purpose: '制造渴望、品牌片', advice: '展示理想结果，让用户看见想成为的自己', frequency: '每月 1 条' }
};

const questions = [
  ['行业与产品', '你的行业赛道是？', [['美业 / 护肤 / 穿搭 / 医美', '喜+2，欲+1，爱+1'], ['大健康 / 养生 / 营养 / 中医', '喜+1，爱+1，惧+1'], ['疗愈 / 心理咨询 / 身心灵', '爱+2，哀+1，喜+1'], ['教育 / 教培 / 学科辅导', '惧+2，喜+1，怒+1'], ['心理学 / 情感咨询 / 婚姻修复', '爱+2，哀+2'], ['律师 / 法律咨询', '惧+1，恶+1，怒+1'], ['保险 / 理财 / 财富管理', '惧+2，喜+1，恶+1'], ['工厂老板 / 实体老板 / 传统企业主', '怒+1，恶+1，喜+1'], ['IP知识付费教学 / 操盘手 / 自媒体教练', '怒+2，恶+1，喜+1'], ['其他行业', '根据产品判断']], 'multi', 2],
  ['行业与产品', '你的核心产品主要帮用户解决什么？', [['帮人赚钱 / 提升收入', '怒+2，恶+1，喜+1'], ['帮人变美 / 变好 / 变健康', '喜+2，欲+1，爱+1'], ['帮人安心 / 缓解焦虑 / 疗愈', '爱+2，哀+1'], ['帮人省时间 / 避坑 / 少走弯路', '惧+1，怒+1，恶+1']], 'multi', 2],
  ['行业与产品', '你的客单价属于？', [['1–5000 元', '爱+2，哀+1，惧+1'], ['5000–1 万', '喜+1，欲+1，爱+1'], ['1 万–5 万', '恶+2，怒+1，喜+1'], ['5 万–10 万', '恶+2，怒+2'], ['10 万以上', '恶+2，怒+2，喜+1']], 'multi', 2],
  ['行业与产品', '你的交付方式是？', [['一对一深度服务（陪跑 / 私教 / 咨询）', '恶+1，爱+1，喜+1'], ['一对多课程 / 训练营', '惧+1，喜+1，怒+1'], ['社群 / 会员制陪伴', '爱+2，哀+1'], ['内容 / 工具 / 模板类产品', '喜+1，欲+1，惧+1']], 'multi', 2],
  ['用户心理', '你的用户最怕失去什么？', [['怕失去钱 / 机会', '惧+2'], ['怕被人评判 / 不被接纳', '爱+1，哀+2'], ['怕走弯路 / 被割韭菜', '怒+2，恶+1'], ['怕平庸 / 没结果', '喜+1，欲+2']], 'multi', 2],
  ['用户心理', '你的用户最想得到什么？', [['想赚钱 / 想成功', '怒+1，喜+2，欲+1'], ['想变美 / 变自信', '喜+2，欲+2'], ['想安心 / 想被理解', '爱+2，哀+1'], ['想少走弯路 / 想有人带', '惧+1，恶+1，喜+1']], 'multi', 2],
  ['用户心理', '你的用户决定付费时，最大的障碍是什么？', [['怕花钱没效果', '惧+2'], ['怕自己坚持不下来', '惧+1，哀+1'], ['怕遇到不靠谱的人', '怒+2，恶+1'], ['怕现在不是最好时机', '惧+1，欲+1'], ['觉得价格太高', '恶+1，喜+1'], ['怕身边人笑话', '爱+2，哀+1'], ['不知道该选谁', '恶+2，怒+1'], ['之前买过类似的没效果', '怒+2，哀+1'], ['怕错过机会', '欲+2，惧+1'], ['其他障碍', '根据情况判断']], 'multi', 3],
  ['个人特质', '你平时的说话风格是？', [['语速快、犀利、一针见血', '怒+2，恶+1'], ['语速慢、温柔、娓娓道来', '爱+2，哀+1'], ['轻快、幽默、有感染力', '喜+2，欲+1'], ['沉稳、权威、逻辑严密', '惧+1，恶+1，喜+1']], 'multi', 2],
  ['个人特质', '你生气的时候通常会？', [['直接表达，不怕冲突', '怒+2，恶+1'], ['忍着不说，自己消化', '哀+2，爱+1'], ['用幽默化解', '喜+1，欲+1'], ['冷静分析，讲道理', '惧+1，恶+1']], 'single', 1],
  ['个人特质', '你讲自己经历时，更偏向？', [['平静叙述，像讲故事', '哀+2，爱+1'], ['有情绪起伏，像演讲', '怒+1，喜+1，欲+1'], ['轻描淡写，不渲染', '恶+1，喜+1'], ['逻辑清晰，像上课', '惧+1，恶+1']], 'multi', 2],
  ['个人特质', '你的长相 / 气质更接近？', [['气场强、干练、有距离感', '恶+2，怒+1'], ['亲和、温暖、邻家感', '爱+2，哀+1'], ['阳光、活力、有能量', '喜+2，欲+1'], ['知性、专业、可信赖', '惧+1，喜+1']], 'multi', 2],
  ['个人特质', '你面对镜头时，最自然的状态是？', [['直接开怼，敢说真话', '怒+2，恶+1'], ['温柔分享，像跟朋友聊天', '爱+2，哀+1'], ['自信展示，晒结果', '喜+2，欲+1'], ['严肃分析，给干货', '惧+1，恶+1']], 'multi', 2],
  ['个人特质', '你更喜欢哪种表达方式？', [['讲观点、亮态度', '怒+2，恶+1'], ['讲故事、讲经历', '哀+2，爱+1'], ['讲结果、讲案例', '喜+2，欲+1'], ['讲方法、讲逻辑', '惧+1，恶+1']], 'multi', 2],
  ['八字五行 · 可选', '你的日主五行是？', [['火（丙、丁）', '怒+2，喜+1'], ['土（戊、己）', '恶+1，喜+1'], ['木（甲、乙）', '怒+1，欲+1'], ['水（壬、癸）', '哀+1，爱+1'], ['金（庚、辛）', '惧+1，恶+1']], 'single', 1],
  ['八字五行 · 可选', '你的八字身强还是身弱？', [['身强', '怒+1，喜+1，恶+1'], ['身弱', '哀+1，爱+1，惧+1']], 'single', 1]
];

let current = 0;
let answers = Array.from({ length: questions.length }, () => []);
const scores = () => Object.fromEntries(Object.keys(emotions).map(key => [key, 0]));
const $ = id => document.getElementById(id);
const scoreFromText = text => { const result = {}; [...text.matchAll(/([怒喜哀惧爱恶欲])\+(\d)/g)].forEach(match => { result[match[1]] = Number(match[2]); }); return result; };

function show(id) { ['introView', 'quizView', 'resultView'].forEach(view => $(view).classList.toggle('hidden', view !== id)); }
function showToast(message) { const toast = $('toast'); toast.textContent = message; toast.classList.add('visible'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('visible'), 2400); }
function makeShareUrl(includeAnswers = false) { const url = new URL(window.location.href); url.hash = ''; if (includeAnswers) url.searchParams.set('answers', answers.map(selection => selection.length ? selection.reduce((mask, index) => mask | (1 << index), 0) : 'x').join('.')); return url.toString(); }
async function shareUrl(url, message) { try { if (navigator.share) { await navigator.share({ title: '创始人 IP 情绪风格测评', text: message, url }); } else { await navigator.clipboard.writeText(url); showToast('分享链接已复制，发给学员即可'); } } catch (error) { if (error.name !== 'AbortError') { try { await navigator.clipboard.writeText(url); showToast('分享链接已复制'); } catch (clipboardError) { showToast('请复制浏览器地址栏链接分享'); } } } }
function openShareModal() { const url = makeShareUrl(); $('shareUrlInput').value = url; $('shareQrImage').src = `https://quickchart.io/qr?size=260&margin=2&text=${encodeURIComponent(url)}`; $('shareModal').classList.remove('hidden'); document.body.classList.add('modal-open'); }
function closeShareModal() { $('shareModal').classList.add('hidden'); document.body.classList.remove('modal-open'); }
async function copyShareUrl() { const url = $('shareUrlInput').value; try { await navigator.clipboard.writeText(url); } catch (error) { $('shareUrlInput').select(); document.execCommand('copy'); } showToast('测评网址已复制'); }
function downloadQr() { const link = document.createElement('a'); link.download = '创始人IP情绪风格测评二维码.png'; link.href = $('shareQrImage').src; link.target = '_blank'; link.click(); }
function loadSharedResult() { const encoded = new URLSearchParams(window.location.search).get('answers'); if (!encoded || !/^[0-9x]+(?:\.[0-9x]+)*$/.test(encoded)) return false; const tokens = encoded.includes('.') ? encoded.split('.') : [...encoded]; if (tokens.length !== questions.length) return false; if (tokens.some((token, index) => token !== 'x' && Number(token) > (1 << questions[index][2].length) - 1)) return false; answers = tokens.map((token, index) => { if (token === 'x') return []; const mask = Number(token); return Array.from({ length: questions[index][2].length }, (_, optionIndex) => optionIndex).filter(optionIndex => mask & (1 << optionIndex)); }); renderResults(); show('resultView'); $('headerStatus').textContent = '已打开分享结果'; return true; }
function renderQuestion() {
  const [section, title, options, mode, maxSelection] = questions[current];
  $('sectionLabel').textContent = `${current < 4 ? '第一部分' : current < 7 ? '第二部分' : current < 13 ? '第三部分' : '第四部分'} · ${section}`;
  $('questionTitle').textContent = title; $('currentNumber').textContent = String(current + 1).padStart(2, '0'); $('progressBar').style.width = `${((current + 1) / questions.length) * 100}%`; $('skipHint').textContent = mode === 'single' ? '单选题 · 请选择最符合的一项' : `多选题 · 最多选择 ${maxSelection} 项`;
  $('options').innerHTML = options.map((option, index) => `<div class="option ${answers[current].includes(index) ? 'selected' : ''}" data-index="${index}"><span class="option-letter">${answers[current].includes(index) ? '✓' : String.fromCharCode(65 + index)}</span><div class="option-copy"><strong>${option[0]}</strong></div></div>`).join('');
  document.querySelectorAll('.option').forEach(option => option.addEventListener('click', () => { const index = Number(option.dataset.index); const selected = answers[current]; if (selected.includes(index)) answers[current] = selected.filter(item => item !== index); else if (mode === 'single') answers[current] = [index]; else if (selected.length < maxSelection) answers[current] = [...selected, index]; else { showToast(`本题最多选择 ${maxSelection} 项`); return; } renderQuestion(); }));
  $('prevButton').disabled = current === 0; $('nextButton').disabled = answers[current].length === 0; $('nextButton').innerHTML = current === questions.length - 1 ? '查看结果 <span>↗</span>' : '下一题 <span>→</span>';
}
function calculate() { const total = scores(); answers.forEach((selection, questionIndex) => selection.forEach(answer => Object.entries(scoreFromText(questions[questionIndex][2][answer][1])).forEach(([emotion, value]) => { total[emotion] += value; }))); return Object.entries(total).sort((a, b) => b[1] - a[1]); }
function renderResults() {
  const ranked = calculate(); const primary = ranked[0][0]; const support = ranked.slice(1, 3).map(item => item[0]); const avoid = ranked.slice(-2).map(item => item[0]); const max = ranked[0][1] || 1;
  $('dominantEmotion').textContent = primary; $('dominantType').textContent = emotions[primary].type; $('dominantSummary').textContent = `${emotions[primary].advice}。你的内容首先要让用户感受到${emotions[primary].purpose.replace('建立人设、', '').replace('、替用户说话', '')}。`; $('dominantScore').textContent = `得分 ${ranked[0][1]}`; $('dominantFrequency').textContent = emotions[primary].frequency;
  $('resultTitle').textContent = `${primary} × ${support.join(' × ')} 配方`; $('resultSubtitle').textContent = `${emotions[primary].type}为主，${emotions[support[0]].type}与${emotions[support[1]].type}辅助`;
  $('scoreBars').innerHTML = ranked.map(([emotion, score]) => `<div class="score-bar-row"><strong>${emotion}</strong><div class="score-bar-track"><div class="score-bar-fill" style="width:${Math.max(5, score / max * 100)}%"></div></div><span>${score}</span></div>`).join('');
  $('primaryEmotion').textContent = `${primary} · ${emotions[primary].type}`; $('supportEmotions').textContent = support.map(emotion => `${emotion} · ${emotions[emotion].type}`).join(' + '); $('contentRatio').textContent = '60% + 25% + 15%';
  $('contentAdvice').innerHTML = [primary, ...support].map((emotion, index) => `<div class="advice-item"><strong>${[60, 25, 15][index]}% ${emotion} · ${emotions[emotion].type}</strong><span>${emotions[emotion].advice}。${emotions[emotion].purpose}，建议${emotions[emotion].frequency}。</span></div>`).join(''); $('avoidAdvice').textContent = `${avoid.join('、')}：分数较低，暂时不要把它们当作主要表达。你的内容更适合从「${emotions[primary].type}」出发，保持真实比刻意补齐所有情绪更重要。`; $('completionCopy').textContent = `完成度 ${Math.round(answers.filter(selection => selection.length).length / questions.length * 100)}%`; $('signalCopy').textContent = ranked[0][1] - ranked[1][1] >= 3 ? '情绪信号清晰' : '情绪组合丰富'; $('emotionTags').innerHTML = ranked.slice(0, 4).map(([emotion, score], index) => `<span class="emotion-tag tag-${index}">${emotion} · ${emotions[emotion].type}<b>${score}</b></span>`).join('');
  const profile = [['行业赛道', answerText(0)], ['核心产品', answerText(1)], ['客单价', answerText(2)], ['交付方式', answerText(3)], ['用户最怕', answerText(4)], ['用户最想要', answerText(5)], ['用户决策障碍', answerText(6)], ['说话风格', answerText(7)], ['生气时反应', answerText(8)], ['讲经历方式', answerText(9)], ['气质类型', answerText(10)], ['面对镜头状态', answerText(11)], ['表达方式偏好', answerText(12)], ['主情绪', `${primary} · ${emotions[primary].type}`], ['辅助情绪 1', `${support[0]} · ${emotions[support[0]].type}`], ['辅助情绪 2', `${support[1]} · ${emotions[support[1]].type}`], ['避开情绪', avoid.join('、')], ['主推视频类型', emotions[primary].type], ['内容配比', `${primary} 60% + ${support[0]} 25% + ${support[1]} 15%`]];
  $('profileGrid').innerHTML = profile.map((item, index) => `<div class="profile-item ${index === 12 ? 'wide' : ''}"><span>${item[0]}</span><strong>${item[1]}</strong></div>`).join(''); $('headerStatus').textContent = '测评已完成';
}
function answerText(index) { const selection = answers[index]; return selection.length ? selection.map(answer => questions[index][2][answer][0]).join('、') : '未填写'; }
function ensureResultLayout() { const description = document.querySelector('.intro-description'); const note = document.querySelector('.micro-note'); if (description) description.textContent = '用情绪表达做爆款，用信任表达做成交。10 分钟找到属于你的情绪配方、内容比例和可直接执行的视频方向。'; if (note) note.textContent = '15 题 · 约 10 分钟 · 单选与多选'; if (!$('dominantResult') && $('resultCard')) $('resultCard').insertAdjacentHTML('beforebegin', '<div id="dominantResult" class="dominant-result"><div class="dominant-orb"><span id="dominantEmotion">怒</span><small>主情绪</small></div><div class="dominant-copy"><p class="eyebrow">YOUR DOMINANT SIGNAL</p><h3><strong id="dominantType">立场型</strong>人格</h3><p id="dominantSummary">你最适合用清晰的立场和边界，让用户迅速记住你。</p><div class="dominant-meta"><span id="dominantScore">得分 0</span><span id="dominantFrequency">每周 1–2 条</span></div></div><div class="dominant-badge">TOP<br><strong>01</strong></div></div>'); }
function downloadResult() { const canvas = document.createElement('canvas'); canvas.width = 1200; canvas.height = 760; const context = canvas.getContext('2d'); context.fillStyle = '#202320'; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#d8ef72'; context.fillRect(70, 72, 95, 10); context.fillStyle = '#f4f1ea'; context.font = '700 24px sans-serif'; context.fillText('FOUNDER IP PROFILE', 70, 145); context.font = '600 58px serif'; context.fillText($('resultTitle').textContent, 70, 215); context.fillStyle = '#aeb3a9'; context.font = '20px sans-serif'; context.fillText($('resultSubtitle').textContent, 70, 255); const rows = [...document.querySelectorAll('.score-bar-row')]; rows.forEach((row, index) => { const y = 335 + index * 38; context.fillStyle = '#f4f1ea'; context.font = '700 18px sans-serif'; context.fillText(row.children[0].textContent, 75, y); context.fillStyle = '#424940'; context.fillRect(125, y - 14, 700, 11); context.fillStyle = '#d8ef72'; context.fillRect(125, y - 14, 700 * parseFloat(row.children[1].firstElementChild.style.width) / 100, 11); context.fillStyle = '#aeb3a9'; context.font = '16px sans-serif'; context.fillText(row.children[2].textContent, 850, y); }); context.fillStyle = '#ff795f'; context.font = '700 22px sans-serif'; context.fillText('内容配比  60% + 25% + 15%', 70, 680); context.fillStyle = '#aeb3a9'; context.font = '16px sans-serif'; context.fillText('创始人 IP 情绪风格测评 · 保存于你的内容档案', 70, 720); const link = document.createElement('a'); link.download = '创始人IP情绪风格测评结果.png'; link.href = canvas.toDataURL('image/png'); link.click(); }

function downloadResult() {
  const canvas = document.createElement('canvas'); canvas.width = 1400; canvas.height = 1780; const context = canvas.getContext('2d'); const ranked = calculate(); const primary = ranked[0][0];
  const rounded = (x, y, width, height, radius, fill, stroke) => { context.beginPath(); context.roundRect(x, y, width, height, radius); context.fillStyle = fill; context.fill(); if (stroke) { context.strokeStyle = stroke; context.stroke(); } };
  const wrapped = (text, x, y, width, lineHeight, color, font) => { context.fillStyle = color; context.font = font; let line = ''; let cursorY = y; [...text].forEach(character => { const next = line + character; if (context.measureText(next).width > width && line) { context.fillText(line, x, cursorY); line = character; cursorY += lineHeight; } else line = next; }); if (line) context.fillText(line, x, cursorY); return cursorY; };
  context.fillStyle = '#f6f1fb'; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#e7d7ff'; context.fillRect(0, 0, canvas.width, 290); context.fillStyle = '#6d43d9'; context.fillRect(82, 75, 118, 12); context.fillStyle = '#211b32'; context.font = '700 24px sans-serif'; context.fillText('FOUNDER IP / EMOTIONAL POSITIONING', 82, 135); context.font = '600 58px serif'; context.fillText('创始人 IP 情绪风格报告', 82, 210); context.fillStyle = '#777083'; context.font = '20px sans-serif'; context.fillText('用情绪表达做爆款，用信任表达做成交。', 84, 252);
  rounded(70, 330, 1260, 310, 28, '#2b1d43'); context.fillStyle = '#d9f47b'; context.font = '700 18px sans-serif'; context.fillText('YOUR DOMINANT SIGNAL · TOP 01', 110, 390); context.fillStyle = '#ffffff'; context.font = '600 70px serif'; context.fillText(`${primary}型人格`, 110, 480); wrapped(`${emotions[primary].advice}。你的内容首先要让用户感受到${emotions[primary].purpose.replace('建立人设、', '').replace('、替用户说话', '')}。`, 112, 535, 760, 34, '#ded1ea', '20px sans-serif'); context.fillStyle = '#d9f47b'; context.beginPath(); context.arc(1160, 470, 105, 0, Math.PI * 2); context.fill(); context.fillStyle = '#2b1d43'; context.textAlign = 'center'; context.font = '700 74px serif'; context.fillText(primary, 1160, 490); context.font = '16px sans-serif'; context.fillText(`${emotions[primary].type} · 得分 ${ranked[0][1]}`, 1160, 530); context.textAlign = 'left';
  context.fillStyle = '#777083'; context.font = '700 16px sans-serif'; context.fillText('七情绪分布 · 从高到低', 82, 705); ranked.forEach(([emotion, score], index) => { const y = 765 + index * 45; context.fillStyle = '#211b32'; context.font = '700 19px sans-serif'; context.fillText(`${String(index + 1).padStart(2, '0')}  ${emotion}`, 90, y); rounded(230, y - 18, 760, 14, 7, '#e1d9eb'); rounded(230, y - 18, Math.max(25, 760 * score / (ranked[0][1] || 1)), 14, 7, index === 0 ? '#6d43d9' : '#b175d8'); context.fillStyle = '#777083'; context.font = '16px sans-serif'; context.fillText(`${score} · ${emotions[emotion].type}`, 1030, y); });
  rounded(70, 1135, 600, 270, 22, '#ffffff', '#ded6ea'); rounded(700, 1135, 630, 270, 22, '#ffffff', '#ded6ea'); context.fillStyle = '#6d43d9'; context.font = '700 15px sans-serif'; context.fillText('CONTENT DIRECTION', 105, 1185); context.fillStyle = '#211b32'; context.font = '600 29px serif'; context.fillText('内容配比', 105, 1235); context.font = '700 22px sans-serif'; context.fillText(`${primary} 60% + ${ranked[1][0]} 25% + ${ranked[2][0]} 15%`, 105, 1290); wrapped(`主情绪：${emotions[primary].advice}。辅助情绪：${emotions[ranked[1][0]].advice}。`, 105, 1345, 500, 28, '#777083', '17px sans-serif'); context.fillStyle = '#6d43d9'; context.font = '700 15px sans-serif'; context.fillText('ACTION NOTES', 735, 1185); context.fillStyle = '#211b32'; context.font = '600 29px serif'; context.fillText('下一步这样拍', 735, 1235); wrapped(`主推类型：${emotions[primary].type}。${emotions[primary].purpose}。${emotions[primary].frequency}。`, 735, 1290, 520, 28, '#777083', '17px sans-serif');
  context.fillStyle = '#777083'; context.font = '700 15px sans-serif'; context.fillText('IP 情绪风格档案卡', 82, 1500); const profileRows = [...document.querySelectorAll('.profile-item')].slice(0, 9); profileRows.forEach((item, index) => { const x = 82 + (index % 3) * 425; const y = 1540 + Math.floor(index / 3) * 62; context.fillStyle = '#777083'; context.font = '13px sans-serif'; context.fillText(item.querySelector('span').textContent, x, y); context.fillStyle = '#211b32'; context.font = '600 16px sans-serif'; context.fillText(item.querySelector('strong').textContent.slice(0, 22), x, y + 26); }); context.fillStyle = '#aaa0b4'; context.font = '14px sans-serif'; context.fillText('创始人 IP 情绪风格测评 · 结果报告', 82, 1740);
  const link = document.createElement('a'); link.download = '创始人IP情绪风格完整结果报告.png'; link.href = canvas.toDataURL('image/png'); link.click();
}

ensureResultLayout(); $('startButton').addEventListener('click', () => { current = 0; answers = Array.from({ length: questions.length }, () => []); show('quizView'); $('headerStatus').textContent = '正在测评'; renderQuestion(); }); $('prevButton').addEventListener('click', () => { if (current > 0) { current--; renderQuestion(); } }); $('nextButton').addEventListener('click', () => { if (current < questions.length - 1) { current++; renderQuestion(); } else { renderResults(); show('resultView'); window.scrollTo({ top: 0, behavior: 'smooth' }); } }); $('restartButton').addEventListener('click', () => { show('introView'); $('headerStatus').textContent = '准备开始'; window.history.replaceState({}, '', window.location.pathname); window.scrollTo({ top: 0, behavior: 'smooth' }); }); $('saveImageButton').addEventListener('click', downloadResult); loadSharedResult();const emotions = {
  æ€’: { type: 'ç«‹åœºåž‹', purpose: 'å»ºç«‹äººè®¾ã€æ›¿ç”¨æˆ·è¯´è¯', advice: 'äº®æ€åº¦ã€åˆ’è¾¹ç•Œã€æ›¿ç”¨æˆ·è¯´è¯', frequency: 'æ¯å‘¨ 1â€“2 æ¡' },
  å–œ: { type: 'ç»“æžœåž‹', purpose: 'æ™’æˆæžœã€ç»™å¸Œæœ›', advice: 'æ™’æˆ˜ç»©ã€æ™’å­¦å‘˜æ¡ˆä¾‹ï¼Œç»™å¸Œæœ›', frequency: 'æ¯å‘¨ 1 æ¡' },
  å“€: { type: 'æ•…äº‹åž‹', purpose: 'æ‹‰ä¿¡ä»»ã€è®²ç»åŽ†', advice: 'è®²è½¬æŠ˜ã€è®²çœŸå®žç»åŽ†ï¼Œè®©äººçœ‹è§ä½ çš„æ¥è·¯', frequency: 'æ¯ä¸¤å‘¨ 1 æ¡' },
  æƒ§: { type: 'ç—›ç‚¹åž‹', purpose: 'åˆ¶é€ ç´§è¿«æ„Ÿã€å¼•æµ', advice: 'ç‚¹å‡ºé£Žé™©ï¼Œä½†ä¸è¦æŒç»­åˆ¶é€ ç„¦è™‘', frequency: 'å‘å”®å‰é›†ä¸­ç”¨' },
  çˆ±: { type: 'é™ªä¼´åž‹', purpose: 'æ‹‰è¿‘è·ç¦»ã€ç¤¾ç¾¤ç»´æŠ¤', advice: 'å¤šå›žåº”ã€å¤šåˆ†äº«å¹•åŽï¼Œè®©ç”¨æˆ·æ„Ÿåˆ°è¢«æŽ¥ä½', frequency: 'æ¯å‘¨ 1 æ¡' },
  æ¶: { type: 'ç­›é€‰åž‹', purpose: 'å»ºç«‹é«˜ç«¯æ„Ÿã€ç­›é€‰å®¢æˆ·', advice: 'è¯´æ¸…æ¥šä¸æœåŠ¡è°ï¼Œå»ºç«‹è¾¹ç•Œä¸Žä¸“ä¸šæ„Ÿ', frequency: 'å‘å”®å‰é›†ä¸­ç”¨' },
  æ¬²: { type: 'å‘å¾€åž‹', purpose: 'åˆ¶é€ æ¸´æœ›ã€å“ç‰Œç‰‡', advice: 'å±•ç¤ºç†æƒ³ç»“æžœï¼Œè®©ç”¨æˆ·çœ‹è§æƒ³æˆä¸ºçš„è‡ªå·±', frequency: 'æ¯æœˆ 1 æ¡' }
};

const questions = [
  ['è¡Œä¸šä¸Žäº§å“', 'ä½ çš„è¡Œä¸šèµ›é“æ˜¯ï¼Ÿ', [['ç¾Žä¸š / æŠ¤è‚¤ / ç©¿æ­ / åŒ»ç¾Ž', 'å–œ+2ï¼Œæ¬²+1ï¼Œçˆ±+1'], ['å¤§å¥åº· / å…»ç”Ÿ / è¥å…» / ä¸­åŒ»', 'å–œ+1ï¼Œçˆ±+1ï¼Œæƒ§+1'], ['ç–—æ„ˆ / å¿ƒç†å’¨è¯¢ / èº«å¿ƒçµ', 'çˆ±+2ï¼Œå“€+1ï¼Œå–œ+1'], ['æ•™è‚² / æ•™åŸ¹ / å­¦ç§‘è¾…å¯¼', 'æƒ§+2ï¼Œå–œ+1ï¼Œæ€’+1'], ['å¿ƒç†å­¦ / æƒ…æ„Ÿå’¨è¯¢ / å©šå§»ä¿®å¤', 'çˆ±+2ï¼Œå“€+2'], ['å¾‹å¸ˆ / æ³•å¾‹å’¨è¯¢', 'æƒ§+1ï¼Œæ¶+1ï¼Œæ€’+1'], ['ä¿é™© / ç†è´¢ / è´¢å¯Œç®¡ç†', 'æƒ§+2ï¼Œå–œ+1ï¼Œæ¶+1'], ['å·¥åŽ‚è€æ¿ / å®žä½“è€æ¿ / ä¼ ç»Ÿä¼ä¸šä¸»', 'æ€’+1ï¼Œæ¶+1ï¼Œå–œ+1'], ['IPçŸ¥è¯†ä»˜è´¹æ•™å­¦ / æ“ç›˜æ‰‹ / è‡ªåª’ä½“æ•™ç»ƒ', 'æ€’+2ï¼Œæ¶+1ï¼Œå–œ+1'], ['å…¶ä»–è¡Œä¸š', 'æ ¹æ®äº§å“åˆ¤æ–­']], 'multi', 2],
  ['è¡Œä¸šä¸Žäº§å“', 'ä½ çš„æ ¸å¿ƒäº§å“ä¸»è¦å¸®ç”¨æˆ·è§£å†³ä»€ä¹ˆï¼Ÿ', [['å¸®äººèµšé’± / æå‡æ”¶å…¥', 'æ€’+2ï¼Œæ¶+1ï¼Œå–œ+1'], ['å¸®äººå˜ç¾Ž / å˜å¥½ / å˜å¥åº·', 'å–œ+2ï¼Œæ¬²+1ï¼Œçˆ±+1'], ['å¸®äººå®‰å¿ƒ / ç¼“è§£ç„¦è™‘ / ç–—æ„ˆ', 'çˆ±+2ï¼Œå“€+1'], ['å¸®äººçœæ—¶é—´ / é¿å‘ / å°‘èµ°å¼¯è·¯', 'æƒ§+1ï¼Œæ€’+1ï¼Œæ¶+1']], 'multi', 2],
  ['è¡Œä¸šä¸Žäº§å“', 'ä½ çš„å®¢å•ä»·å±žäºŽï¼Ÿ', [['1â€“5000 å…ƒ', 'çˆ±+2ï¼Œå“€+1ï¼Œæƒ§+1'], ['5000â€“1 ä¸‡', 'å–œ+1ï¼Œæ¬²+1ï¼Œçˆ±+1'], ['1 ä¸‡â€“5 ä¸‡', 'æ¶+2ï¼Œæ€’+1ï¼Œå–œ+1'], ['5 ä¸‡â€“10 ä¸‡', 'æ¶+2ï¼Œæ€’+2'], ['10 ä¸‡ä»¥ä¸Š', 'æ¶+2ï¼Œæ€’+2ï¼Œå–œ+1']], 'multi', 2],
  ['è¡Œä¸šä¸Žäº§å“', 'ä½ çš„äº¤ä»˜æ–¹å¼æ˜¯ï¼Ÿ', [['ä¸€å¯¹ä¸€æ·±åº¦æœåŠ¡ï¼ˆé™ªè·‘ / ç§æ•™ / å’¨è¯¢ï¼‰', 'æ¶+1ï¼Œçˆ±+1ï¼Œå–œ+1'], ['ä¸€å¯¹å¤šè¯¾ç¨‹ / è®­ç»ƒè¥', 'æƒ§+1ï¼Œå–œ+1ï¼Œæ€’+1'], ['ç¤¾ç¾¤ / ä¼šå‘˜åˆ¶é™ªä¼´', 'çˆ±+2ï¼Œå“€+1'], ['å†…å®¹ / å·¥å…· / æ¨¡æ¿ç±»äº§å“', 'å–œ+1ï¼Œæ¬²+1ï¼Œæƒ§+1']], 'multi', 2],
  ['ç”¨æˆ·å¿ƒç†', 'ä½ çš„ç”¨æˆ·æœ€æ€•å¤±åŽ»ä»€ä¹ˆï¼Ÿ', [['æ€•å¤±åŽ»é’± / æœºä¼š', 'æƒ§+2'], ['æ€•è¢«äººè¯„åˆ¤ / ä¸è¢«æŽ¥çº³', 'çˆ±+1ï¼Œå“€+2'], ['æ€•èµ°å¼¯è·¯ / è¢«å‰²éŸ­èœ', 'æ€’+2ï¼Œæ¶+1'], ['æ€•å¹³åº¸ / æ²¡ç»“æžœ', 'å–œ+1ï¼Œæ¬²+2']], 'multi', 2],
  ['ç”¨æˆ·å¿ƒç†', 'ä½ çš„ç”¨æˆ·æœ€æƒ³å¾—åˆ°ä»€ä¹ˆï¼Ÿ', [['æƒ³èµšé’± / æƒ³æˆåŠŸ', 'æ€’+1ï¼Œå–œ+2ï¼Œæ¬²+1'], ['æƒ³å˜ç¾Ž / å˜è‡ªä¿¡', 'å–œ+2ï¼Œæ¬²+2'], ['æƒ³å®‰å¿ƒ / æƒ³è¢«ç†è§£', 'çˆ±+2ï¼Œå“€+1'], ['æƒ³å°‘èµ°å¼¯è·¯ / æƒ³æœ‰äººå¸¦', 'æƒ§+1ï¼Œæ¶+1ï¼Œå–œ+1']], 'multi', 2],
  ['ç”¨æˆ·å¿ƒç†', 'ä½ çš„ç”¨æˆ·å†³å®šä»˜è´¹æ—¶ï¼Œæœ€å¤§çš„éšœç¢æ˜¯ä»€ä¹ˆï¼Ÿ', [['æ€•èŠ±é’±æ²¡æ•ˆæžœ', 'æƒ§+2'], ['æ€•è‡ªå·±åšæŒä¸ä¸‹æ¥', 'æƒ§+1ï¼Œå“€+1'], ['æ€•é‡åˆ°ä¸é è°±çš„äºº', 'æ€’+2ï¼Œæ¶+1'], ['æ€•çŽ°åœ¨ä¸æ˜¯æœ€å¥½æ—¶æœº', 'æƒ§+1ï¼Œæ¬²+1'], ['è§‰å¾—ä»·æ ¼å¤ªé«˜', 'æ¶+1ï¼Œå–œ+1'], ['æ€•èº«è¾¹äººç¬‘è¯', 'çˆ±+2ï¼Œå“€+1'], ['ä¸çŸ¥é“è¯¥é€‰è°', 'æ¶+2ï¼Œæ€’+1'], ['ä¹‹å‰ä¹°è¿‡ç±»ä¼¼çš„æ²¡æ•ˆæžœ', 'æ€’+2ï¼Œå“€+1'], ['æ€•é”™è¿‡æœºä¼š', 'æ¬²+2ï¼Œæƒ§+1'], ['å…¶ä»–éšœç¢', 'æ ¹æ®æƒ…å†µåˆ¤æ–­']], 'multi', 3],
  ['ä¸ªäººç‰¹è´¨', 'ä½ å¹³æ—¶çš„è¯´è¯é£Žæ ¼æ˜¯ï¼Ÿ', [['è¯­é€Ÿå¿«ã€çŠ€åˆ©ã€ä¸€é’ˆè§è¡€', 'æ€’+2ï¼Œæ¶+1'], ['è¯­é€Ÿæ…¢ã€æ¸©æŸ”ã€å¨“å¨“é“æ¥', 'çˆ±+2ï¼Œå“€+1'], ['è½»å¿«ã€å¹½é»˜ã€æœ‰æ„ŸæŸ“åŠ›', 'å–œ+2ï¼Œæ¬²+1'], ['æ²‰ç¨³ã€æƒå¨ã€é€»è¾‘ä¸¥å¯†', 'æƒ§+1ï¼Œæ¶+1ï¼Œå–œ+1']], 'multi', 2],
  ['ä¸ªäººç‰¹è´¨', 'ä½ ç”Ÿæ°”çš„æ—¶å€™é€šå¸¸ä¼šï¼Ÿ', [['ç›´æŽ¥è¡¨è¾¾ï¼Œä¸æ€•å†²çª', 'æ€’+2ï¼Œæ¶+1'], ['å¿ç€ä¸è¯´ï¼Œè‡ªå·±æ¶ˆåŒ–', 'å“€+2ï¼Œçˆ±+1'], ['ç”¨å¹½é»˜åŒ–è§£', 'å–œ+1ï¼Œæ¬²+1'], ['å†·é™åˆ†æžï¼Œè®²é“ç†', 'æƒ§+1ï¼Œæ¶+1']], 'single', 1],
  ['ä¸ªäººç‰¹è´¨', 'ä½ è®²è‡ªå·±ç»åŽ†æ—¶ï¼Œæ›´åå‘ï¼Ÿ', [['å¹³é™å™è¿°ï¼Œåƒè®²æ•…äº‹', 'å“€+2ï¼Œçˆ±+1'], ['æœ‰æƒ…ç»ªèµ·ä¼ï¼Œåƒæ¼”è®²', 'æ€’+1ï¼Œå–œ+1ï¼Œæ¬²+1'], ['è½»ææ·¡å†™ï¼Œä¸æ¸²æŸ“', 'æ¶+1ï¼Œå–œ+1'], ['é€»è¾‘æ¸…æ™°ï¼Œåƒä¸Šè¯¾', 'æƒ§+1ï¼Œæ¶+1']], 'multi', 2],
  ['ä¸ªäººç‰¹è´¨', 'ä½ çš„é•¿ç›¸ / æ°”è´¨æ›´æŽ¥è¿‘ï¼Ÿ', [['æ°”åœºå¼ºã€å¹²ç»ƒã€æœ‰è·ç¦»æ„Ÿ', 'æ¶+2ï¼Œæ€’+1'], ['äº²å’Œã€æ¸©æš–ã€é‚»å®¶æ„Ÿ', 'çˆ±+2ï¼Œå“€+1'], ['é˜³å…‰ã€æ´»åŠ›ã€æœ‰èƒ½é‡', 'å–œ+2ï¼Œæ¬²+1'], ['çŸ¥æ€§ã€ä¸“ä¸šã€å¯ä¿¡èµ–', 'æƒ§+1ï¼Œå–œ+1']], 'multi', 2],
  ['ä¸ªäººç‰¹è´¨', 'ä½ é¢å¯¹é•œå¤´æ—¶ï¼Œæœ€è‡ªç„¶çš„çŠ¶æ€æ˜¯ï¼Ÿ', [['ç›´æŽ¥å¼€æ€¼ï¼Œæ•¢è¯´çœŸè¯', 'æ€’+2ï¼Œæ¶+1'], ['æ¸©æŸ”åˆ†äº«ï¼Œåƒè·Ÿæœ‹å‹èŠå¤©', 'çˆ±+2ï¼Œå“€+1'], ['è‡ªä¿¡å±•ç¤ºï¼Œæ™’ç»“æžœ', 'å–œ+2ï¼Œæ¬²+1'], ['ä¸¥è‚ƒåˆ†æžï¼Œç»™å¹²è´§', 'æƒ§+1ï¼Œæ¶+1']], 'multi', 2],
  ['ä¸ªäººç‰¹è´¨', 'ä½ æ›´å–œæ¬¢å“ªç§è¡¨è¾¾æ–¹å¼ï¼Ÿ', [['è®²è§‚ç‚¹ã€äº®æ€åº¦', 'æ€’+2ï¼Œæ¶+1'], ['è®²æ•…äº‹ã€è®²ç»åŽ†', 'å“€+2ï¼Œçˆ±+1'], ['è®²ç»“æžœã€è®²æ¡ˆä¾‹', 'å–œ+2ï¼Œæ¬²+1'], ['è®²æ–¹æ³•ã€è®²é€»è¾‘', 'æƒ§+1ï¼Œæ¶+1']], 'multi', 2],
  ['å…«å­—äº”è¡Œ Â· å¯é€‰', 'ä½ çš„æ—¥ä¸»äº”è¡Œæ˜¯ï¼Ÿ', [['ç«ï¼ˆä¸™ã€ä¸ï¼‰', 'æ€’+2ï¼Œå–œ+1'], ['åœŸï¼ˆæˆŠã€å·±ï¼‰', 'æ¶+1ï¼Œå–œ+1'], ['æœ¨ï¼ˆç”²ã€ä¹™ï¼‰', 'æ€’+1ï¼Œæ¬²+1'], ['æ°´ï¼ˆå£¬ã€ç™¸ï¼‰', 'å“€+1ï¼Œçˆ±+1'], ['é‡‘ï¼ˆåºšã€è¾›ï¼‰', 'æƒ§+1ï¼Œæ¶+1']], 'single', 1],
  ['å…«å­—äº”è¡Œ Â· å¯é€‰', 'ä½ çš„å…«å­—èº«å¼ºè¿˜æ˜¯èº«å¼±ï¼Ÿ', [['èº«å¼º', 'æ€’+1ï¼Œå–œ+1ï¼Œæ¶+1'], ['èº«å¼±', 'å“€+1ï¼Œçˆ±+1ï¼Œæƒ§+1']], 'single', 1]
];

let current = 0;
let answers = Array.from({ length: questions.length }, () => []);
const scores = () => Object.fromEntries(Object.keys(emotions).map(key => [key, 0]));
const $ = id => document.getElementById(id);
const scoreFromText = text => { const result = {}; [...text.matchAll(/([æ€’å–œå“€æƒ§çˆ±æ¶æ¬²])\+(\d)/g)].forEach(match => { result[match[1]] = Number(match[2]); }); return result; };

function show(id) { ['introView', 'quizView', 'resultView'].forEach(view => $(view).classList.toggle('hidden', view !== id)); }
function showToast(message) { const toast = $('toast'); toast.textContent = message; toast.classList.add('visible'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('visible'), 2400); }
function makeShareUrl(includeAnswers = false) { const url = new URL(window.location.href); url.hash = ''; if (includeAnswers) url.searchParams.set('answers', answers.map(selection => selection.length ? selection.reduce((mask, index) => mask | (1 << index), 0) : 'x').join('.')); return url.toString(); }
async function shareUrl(url, message) { try { if (navigator.share) { await navigator.share({ title: 'åˆ›å§‹äºº IP æƒ…ç»ªé£Žæ ¼æµ‹è¯„', text: message, url }); } else { await navigator.clipboard.writeText(url); showToast('åˆ†äº«é“¾æŽ¥å·²å¤åˆ¶ï¼Œå‘ç»™å­¦å‘˜å³å¯'); } } catch (error) { if (error.name !== 'AbortError') { try { await navigator.clipboard.writeText(url); showToast('åˆ†äº«é“¾æŽ¥å·²å¤åˆ¶'); } catch (clipboardError) { showToast('è¯·å¤åˆ¶æµè§ˆå™¨åœ°å€æ é“¾æŽ¥åˆ†äº«'); } } } }
function openShareModal() { const url = makeShareUrl(); $('shareUrlInput').value = url; $('shareQrImage').src = `https://quickchart.io/qr?size=260&margin=2&text=${encodeURIComponent(url)}`; $('shareModal').classList.remove('hidden'); document.body.classList.add('modal-open'); }
function closeShareModal() { $('shareModal').classList.add('hidden'); document.body.classList.remove('modal-open'); }
async function copyShareUrl() { const url = $('shareUrlInput').value; try { await navigator.clipboard.writeText(url); } catch (error) { $('shareUrlInput').select(); document.execCommand('copy'); } showToast('æµ‹è¯„ç½‘å€å·²å¤åˆ¶'); }
function downloadQr() { const link = document.createElement('a'); link.download = 'åˆ›å§‹äººIPæƒ…ç»ªé£Žæ ¼æµ‹è¯„äºŒç»´ç .png'; link.href = $('shareQrImage').src; link.target = '_blank'; link.click(); }
function loadSharedResult() { const encoded = new URLSearchParams(window.location.search).get('answers'); if (!encoded || !/^[0-9x]+(?:\.[0-9x]+)*$/.test(encoded)) return false; const tokens = encoded.includes('.') ? encoded.split('.') : [...encoded]; if (tokens.length !== questions.length) return false; if (tokens.some((token, index) => token !== 'x' && Number(token) > (1 << questions[index][2].length) - 1)) return false; answers = tokens.map((token, index) => { if (token === 'x') return []; const mask = Number(token); return Array.from({ length: questions[index][2].length }, (_, optionIndex) => optionIndex).filter(optionIndex => mask & (1 << optionIndex)); }); renderResults(); show('resultView'); $('headerStatus').textContent = 'å·²æ‰“å¼€åˆ†äº«ç»“æžœ'; return true; }
function renderQuestion() {
  const [section, title, options, mode, maxSelection] = questions[current];
  $('sectionLabel').textContent = `${current < 4 ? 'ç¬¬ä¸€éƒ¨åˆ†' : current < 7 ? 'ç¬¬äºŒéƒ¨åˆ†' : current < 13 ? 'ç¬¬ä¸‰éƒ¨åˆ†' : 'ç¬¬å››éƒ¨åˆ†'} Â· ${section}`;
  $('questionTitle').textContent = title; $('currentNumber').textContent = String(current + 1).padStart(2, '0'); $('progressBar').style.width = `${((current + 1) / questions.length) * 100}%`; $('skipHint').textContent = mode === 'single' ? 'å•é€‰é¢˜ Â· è¯·é€‰æ‹©æœ€ç¬¦åˆçš„ä¸€é¡¹' : `å¤šé€‰é¢˜ Â· æœ€å¤šé€‰æ‹© ${maxSelection} é¡¹`;
  $('options').innerHTML = options.map((option, index) => `<div class="option ${answers[current].includes(index) ? 'selected' : ''}" data-index="${index}"><span class="option-letter">${answers[current].includes(index) ? 'âœ“' : String.fromCharCode(65 + index)}</span><div class="option-copy"><strong>${option[0]}</strong></div></div>`).join('');
  document.querySelectorAll('.option').forEach(option => option.addEventListener('click', () => { const index = Number(option.dataset.index); const selected = answers[current]; if (selected.includes(index)) answers[current] = selected.filter(item => item !== index); else if (mode === 'single') answers[current] = [index]; else if (selected.length < maxSelection) answers[current] = [...selected, index]; else { showToast(`æœ¬é¢˜æœ€å¤šé€‰æ‹© ${maxSelection} é¡¹`); return; } renderQuestion(); }));
  $('prevButton').disabled = current === 0; $('nextButton').disabled = answers[current].length === 0; $('nextButton').innerHTML = current === questions.length - 1 ? 'æŸ¥çœ‹ç»“æžœ <span>â†—</span>' : 'ä¸‹ä¸€é¢˜ <span>â†’</span>';
}
function calculate() { const total = scores(); answers.forEach((selection, questionIndex) => selection.forEach(answer => Object.entries(scoreFromText(questions[questionIndex][2][answer][1])).forEach(([emotion, value]) => { total[emotion] += value; }))); return Object.entries(total).sort((a, b) => b[1] - a[1]); }
function renderResults() {
  const ranked = calculate(); const primary = ranked[0][0]; const support = ranked.slice(1, 3).map(item => item[0]); const avoid = ranked.slice(-2).map(item => item[0]); const max = ranked[0][1] || 1;
  $('dominantEmotion').textContent = primary; $('dominantType').textContent = emotions[primary].type; $('dominantSummary').textContent = `${emotions[primary].advice}ã€‚ä½ çš„å†…å®¹é¦–å…ˆè¦è®©ç”¨æˆ·æ„Ÿå—åˆ°${emotions[primary].purpose.replace('å»ºç«‹äººè®¾ã€', '').replace('ã€æ›¿ç”¨æˆ·è¯´è¯', '')}ã€‚`; $('dominantScore').textContent = `å¾—åˆ† ${ranked[0][1]}`; $('dominantFrequency').textContent = emotions[primary].frequency;
  $('resultTitle').textContent = `${primary} Ã— ${support.join(' Ã— ')} é…æ–¹`; $('resultSubtitle').textContent = `${emotions[primary].type}ä¸ºä¸»ï¼Œ${emotions[support[0]].type}ä¸Ž${emotions[support[1]].type}è¾…åŠ©`;
  $('scoreBars').innerHTML = ranked.map(([emotion, score]) => `<div class="score-bar-row"><strong>${emotion}</strong><div class="score-bar-track"><div class="score-bar-fill" style="width:${Math.max(5, score / max * 100)}%"></div></div><span>${score}</span></div>`).join('');
  $('primaryEmotion').textContent = `${primary} Â· ${emotions[primary].type}`; $('supportEmotions').textContent = support.map(emotion => `${emotion} Â· ${emotions[emotion].type}`).join(' + '); $('contentRatio').textContent = '60% + 25% + 15%';
  $('contentAdvice').innerHTML = [primary, ...support].map((emotion, index) => `<div class="advice-item"><strong>${[60, 25, 15][index]}% ${emotion} Â· ${emotions[emotion].type}</strong><span>${emotions[emotion].advice}ã€‚${emotions[emotion].purpose}ï¼Œå»ºè®®${emotions[emotion].frequency}ã€‚</span></div>`).join(''); $('avoidAdvice').textContent = `${avoid.join('ã€')}ï¼šåˆ†æ•°è¾ƒä½Žï¼Œæš‚æ—¶ä¸è¦æŠŠå®ƒä»¬å½“ä½œä¸»è¦è¡¨è¾¾ã€‚ä½ çš„å†…å®¹æ›´é€‚åˆä»Žã€Œ${emotions[primary].type}ã€å‡ºå‘ï¼Œä¿æŒçœŸå®žæ¯”åˆ»æ„è¡¥é½æ‰€æœ‰æƒ…ç»ªæ›´é‡è¦ã€‚`; $('completionCopy').textContent = `å®Œæˆåº¦ ${Math.round(answers.filter(selection => selection.length).length / questions.length * 100)}%`; $('signalCopy').textContent = ranked[0][1] - ranked[1][1] >= 3 ? 'æƒ…ç»ªä¿¡å·æ¸…æ™°' : 'æƒ…ç»ªç»„åˆä¸°å¯Œ'; $('emotionTags').innerHTML = ranked.slice(0, 4).map(([emotion, score], index) => `<span class="emotion-tag tag-${index}">${emotion} Â· ${emotions[emotion].type}<b>${score}</b></span>`).join('');
  const profile = [['è¡Œä¸šèµ›é“', answerText(0)], ['æ ¸å¿ƒäº§å“', answerText(1)], ['å®¢å•ä»·', answerText(2)], ['äº¤ä»˜æ–¹å¼', answerText(3)], ['ç”¨æˆ·æœ€æ€•', answerText(4)], ['ç”¨æˆ·æœ€æƒ³è¦', answerText(5)], ['ç”¨æˆ·å†³ç­–éšœç¢', answerText(6)], ['è¯´è¯é£Žæ ¼', answerText(7)], ['ç”Ÿæ°”æ—¶ååº”', answerText(8)], ['è®²ç»åŽ†æ–¹å¼', answerText(9)], ['æ°”è´¨ç±»åž‹', answerText(10)], ['é¢å¯¹é•œå¤´çŠ¶æ€', answerText(11)], ['è¡¨è¾¾æ–¹å¼åå¥½', answerText(12)], ['ä¸»æƒ…ç»ª', `${primary} Â· ${emotions[primary].type}`], ['è¾…åŠ©æƒ…ç»ª 1', `${support[0]} Â· ${emotions[support[0]].type}`], ['è¾…åŠ©æƒ…ç»ª 2', `${support[1]} Â· ${emotions[support[1]].type}`], ['é¿å¼€æƒ…ç»ª', avoid.join('ã€')], ['ä¸»æŽ¨è§†é¢‘ç±»åž‹', emotions[primary].type], ['å†…å®¹é…æ¯”', `${primary} 60% + ${support[0]} 25% + ${support[1]} 15%`]];
  $('profileGrid').innerHTML = profile.map((item, index) => `<div class="profile-item ${index === 12 ? 'wide' : ''}"><span>${item[0]}</span><strong>${item[1]}</strong></div>`).join(''); $('headerStatus').textContent = 'æµ‹è¯„å·²å®Œæˆ';
}
function answerText(index) { const selection = answers[index]; return selection.length ? selection.map(answer => questions[index][2][answer][0]).join('ã€') : 'æœªå¡«å†™'; }
function ensureResultLayout() { const description = document.querySelector('.intro-description'); const note = document.querySelector('.micro-note'); if (description) description.textContent = 'ç”¨æƒ…ç»ªè¡¨è¾¾åšçˆ†æ¬¾ï¼Œç”¨ä¿¡ä»»è¡¨è¾¾åšæˆäº¤ã€‚10 åˆ†é’Ÿæ‰¾åˆ°å±žäºŽä½ çš„æƒ…ç»ªé…æ–¹ã€å†…å®¹æ¯”ä¾‹å’Œå¯ç›´æŽ¥æ‰§è¡Œçš„è§†é¢‘æ–¹å‘ã€‚'; if (note) note.textContent = '15 é¢˜ Â· çº¦ 10 åˆ†é’Ÿ Â· å•é€‰ä¸Žå¤šé€‰'; if (!$('dominantResult') && $('resultCard')) $('resultCard').insertAdjacentHTML('beforebegin', '<div id="dominantResult" class="dominant-result"><div class="dominant-orb"><span id="dominantEmotion">æ€’</span><small>ä¸»æƒ…ç»ª</small></div><div class="dominant-copy"><p class="eyebrow">YOUR DOMINANT SIGNAL</p><h3><strong id="dominantType">ç«‹åœºåž‹</strong>äººæ ¼</h3><p id="dominantSummary">ä½ æœ€é€‚åˆç”¨æ¸…æ™°çš„ç«‹åœºå’Œè¾¹ç•Œï¼Œè®©ç”¨æˆ·è¿…é€Ÿè®°ä½ä½ ã€‚</p><div class="dominant-meta"><span id="dominantScore">å¾—åˆ† 0</span><span id="dominantFrequency">æ¯å‘¨ 1â€“2 æ¡</span></div></div><div class="dominant-badge">TOP<br><strong>01</strong></div></div>'); }
function downloadResult() { const canvas = document.createElement('canvas'); canvas.width = 1200; canvas.height = 760; const context = canvas.getContext('2d'); context.fillStyle = '#202320'; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#d8ef72'; context.fillRect(70, 72, 95, 10); context.fillStyle = '#f4f1ea'; context.font = '700 24px sans-serif'; context.fillText('FOUNDER IP PROFILE', 70, 145); context.font = '600 58px serif'; context.fillText($('resultTitle').textContent, 70, 215); context.fillStyle = '#aeb3a9'; context.font = '20px sans-serif'; context.fillText($('resultSubtitle').textContent, 70, 255); const rows = [...document.querySelectorAll('.score-bar-row')]; rows.forEach((row, index) => { const y = 335 + index * 38; context.fillStyle = '#f4f1ea'; context.font = '700 18px sans-serif'; context.fillText(row.children[0].textContent, 75, y); context.fillStyle = '#424940'; context.fillRect(125, y - 14, 700, 11); context.fillStyle = '#d8ef72'; context.fillRect(125, y - 14, 700 * parseFloat(row.children[1].firstElementChild.style.width) / 100, 11); context.fillStyle = '#aeb3a9'; context.font = '16px sans-serif'; context.fillText(row.children[2].textContent, 850, y); }); context.fillStyle = '#ff795f'; context.font = '700 22px sans-serif'; context.fillText('å†…å®¹é…æ¯”  60% + 25% + 15%', 70, 680); context.fillStyle = '#aeb3a9'; context.font = '16px sans-serif'; context.fillText('åˆ›å§‹äºº IP æƒ…ç»ªé£Žæ ¼æµ‹è¯„ Â· ä¿å­˜äºŽä½ çš„å†…å®¹æ¡£æ¡ˆ', 70, 720); const link = document.createElement('a'); link.download = 'åˆ›å§‹äººIPæƒ…ç»ªé£Žæ ¼æµ‹è¯„ç»“æžœ.png'; link.href = canvas.toDataURL('image/png'); link.click(); }

function downloadResult() {
  const canvas = document.createElement('canvas'); canvas.width = 1400; canvas.height = 1780; const context = canvas.getContext('2d'); const ranked = calculate(); const primary = ranked[0][0];
  const rounded = (x, y, width, height, radius, fill, stroke) => { context.beginPath(); context.roundRect(x, y, width, height, radius); context.fillStyle = fill; context.fill(); if (stroke) { context.strokeStyle = stroke; context.stroke(); } };
  const wrapped = (text, x, y, width, lineHeight, color, font) => { context.fillStyle = color; context.font = font; let line = ''; let cursorY = y; [...text].forEach(character => { const next = line + character; if (context.measureText(next).width > width && line) { context.fillText(line, x, cursorY); line = character; cursorY += lineHeight; } else line = next; }); if (line) context.fillText(line, x, cursorY); return cursorY; };
  context.fillStyle = '#f6f1fb'; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#e7d7ff'; context.fillRect(0, 0, canvas.width, 290); context.fillStyle = '#6d43d9'; context.fillRect(82, 75, 118, 12); context.fillStyle = '#211b32'; context.font = '700 24px sans-serif'; context.fillText('FOUNDER IP / EMOTIONAL POSITIONING', 82, 135); context.font = '600 58px serif'; context.fillText('åˆ›å§‹äºº IP æƒ…ç»ªé£Žæ ¼æŠ¥å‘Š', 82, 210); context.fillStyle = '#777083'; context.font = '20px sans-serif'; context.fillText('ç”¨æƒ…ç»ªè¡¨è¾¾åšçˆ†æ¬¾ï¼Œç”¨ä¿¡ä»»è¡¨è¾¾åšæˆäº¤ã€‚', 84, 252);
  rounded(70, 330, 1260, 310, 28, '#2b1d43'); context.fillStyle = '#d9f47b'; context.font = '700 18px sans-serif'; context.fillText('YOUR DOMINANT SIGNAL Â· TOP 01', 110, 390); context.fillStyle = '#ffffff'; context.font = '600 70px serif'; context.fillText(`${primary}åž‹äººæ ¼`, 110, 480); wrapped(`${emotions[primary].advice}ã€‚ä½ çš„å†…å®¹é¦–å…ˆè¦è®©ç”¨æˆ·æ„Ÿå—åˆ°${emotions[primary].purpose.replace('å»ºç«‹äººè®¾ã€', '').replace('ã€æ›¿ç”¨æˆ·è¯´è¯', '')}ã€‚`, 112, 535, 760, 34, '#ded1ea', '20px sans-serif'); context.fillStyle = '#d9f47b'; context.beginPath(); context.arc(1160, 470, 105, 0, Math.PI * 2); context.fill(); context.fillStyle = '#2b1d43'; context.textAlign = 'center'; context.font = '700 74px serif'; context.fillText(primary, 1160, 490); context.font = '16px sans-serif'; context.fillText(`${emotions[primary].type} Â· å¾—åˆ† ${ranked[0][1]}`, 1160, 530); context.textAlign = 'left';
  context.fillStyle = '#777083'; context.font = '700 16px sans-serif'; context.fillText('ä¸ƒæƒ…ç»ªåˆ†å¸ƒ Â· ä»Žé«˜åˆ°ä½Ž', 82, 705); ranked.forEach(([emotion, score], index) => { const y = 765 + index * 45; context.fillStyle = '#211b32'; context.font = '700 19px sans-serif'; context.fillText(`${String(index + 1).padStart(2, '0')}  ${emotion}`, 90, y); rounded(230, y - 18, 760, 14, 7, '#e1d9eb'); rounded(230, y - 18, Math.max(25, 760 * score / (ranked[0][1] || 1)), 14, 7, index === 0 ? '#6d43d9' : '#b175d8'); context.fillStyle = '#777083'; context.font = '16px sans-serif'; context.fillText(`${score} Â· ${emotions[emotion].type}`, 1030, y); });
  rounded(70, 1135, 600, 270, 22, '#ffffff', '#ded6ea'); rounded(700, 1135, 630, 270, 22, '#ffffff', '#ded6ea'); context.fillStyle = '#6d43d9'; context.font = '700 15px sans-serif'; context.fillText('CONTENT DIRECTION', 105, 1185); context.fillStyle = '#211b32'; context.font = '600 29px serif'; context.fillText('å†…å®¹é…æ¯”', 105, 1235); context.font = '700 22px sans-serif'; context.fillText(`${primary} 60% + ${ranked[1][0]} 25% + ${ranked[2][0]} 15%`, 105, 1290); wrapped(`ä¸»æƒ…ç»ªï¼š${emotions[primary].advice}ã€‚è¾…åŠ©æƒ…ç»ªï¼š${emotions[ranked[1][0]].advice}ã€‚`, 105, 1345, 500, 28, '#777083', '17px sans-serif'); context.fillStyle = '#6d43d9'; context.font = '700 15px sans-serif'; context.fillText('ACTION NOTES', 735, 1185); context.fillStyle = '#211b32'; context.font = '600 29px serif'; context.fillText('ä¸‹ä¸€æ­¥è¿™æ ·æ‹', 735, 1235); wrapped(`ä¸»æŽ¨ç±»åž‹ï¼š${emotions[primary].type}ã€‚${emotions[primary].purpose}ã€‚${emotions[primary].frequency}ã€‚`, 735, 1290, 520, 28, '#777083', '17px sans-serif');
  context.fillStyle = '#777083'; context.font = '700 15px sans-serif'; context.fillText('IP æƒ…ç»ªé£Žæ ¼æ¡£æ¡ˆå¡', 82, 1500); const profileRows = [...document.querySelectorAll('.profile-item')].slice(0, 9); profileRows.forEach((item, index) => { const x = 82 + (index % 3) * 425; const y = 1540 + Math.floor(index / 3) * 62; context.fillStyle = '#777083'; context.font = '13px sans-serif'; context.fillText(item.querySelector('span').textContent, x, y); context.fillStyle = '#211b32'; context.font = '600 16px sans-serif'; context.fillText(item.querySelector('strong').textContent.slice(0, 22), x, y + 26); }); context.fillStyle = '#aaa0b4'; context.font = '14px sans-serif'; context.fillText('åˆ›å§‹äºº IP æƒ…ç»ªé£Žæ ¼æµ‹è¯„ Â· ç»“æžœæŠ¥å‘Š', 82, 1740);
  const link = document.createElement('a'); link.download = 'åˆ›å§‹äººIPæƒ…ç»ªé£Žæ ¼å®Œæ•´ç»“æžœæŠ¥å‘Š.png'; link.href = canvas.toDataURL('image/png'); link.click();
}

ensureResultLayout(); $('startButton').addEventListener('click', () => { current = 0; answers = Array.from({ length: questions.length }, () => []); show('quizView'); $('headerStatus').textContent = 'æ­£åœ¨æµ‹è¯„'; renderQuestion(); }); $('prevButton').addEventListener('click', () => { if (current > 0) { current--; renderQuestion(); } }); $('nextButton').addEventListener('click', () => { if (current < questions.length - 1) { current++; renderQuestion(); } else { renderResults(); show('resultView'); window.scrollTo({ top: 0, behavior: 'smooth' }); } }); $('restartButton').addEventListener('click', () => { show('introView'); $('headerStatus').textContent = 'å‡†å¤‡å¼€å§‹'; window.history.replaceState({}, '', window.location.pathname); window.scrollTo({ top: 0, behavior: 'smooth' }); }); $('saveImageButton').addEventListener('click', downloadResult); loadSharedResult();const emotions = {
  æ€’: { type: 'ç«‹åœºåž‹', purpose: 'å»ºç«‹äººè®¾ã€æ›¿ç”¨æˆ·è¯´è¯', advice: 'äº®æ€åº¦ã€åˆ’è¾¹ç•Œã€æ›¿ç”¨æˆ·è¯´è¯', frequency: 'æ¯å‘¨ 1â€“2 æ¡' },
  å–œ: { type: 'ç»“æžœåž‹', purpose: 'æ™’æˆæžœã€ç»™å¸Œæœ›', advice: 'æ™’æˆ˜ç»©ã€æ™’å­¦å‘˜æ¡ˆä¾‹ï¼Œç»™å¸Œæœ›', frequency: 'æ¯å‘¨ 1 æ¡' },
  å“€: { type: 'æ•…äº‹åž‹', purpose: 'æ‹‰ä¿¡ä»»ã€è®²ç»åŽ†', advice: 'è®²è½¬æŠ˜ã€è®²çœŸå®žç»åŽ†ï¼Œè®©äººçœ‹è§ä½ çš„æ¥è·¯', frequency: 'æ¯ä¸¤å‘¨ 1 æ¡' },
  æƒ§: { type: 'ç—›ç‚¹åž‹', purpose: 'åˆ¶é€ ç´§è¿«æ„Ÿã€å¼•æµ', advice: 'ç‚¹å‡ºé£Žé™©ï¼Œä½†ä¸è¦æŒç»­åˆ¶é€ ç„¦è™‘', frequency: 'å‘å”®å‰é›†ä¸­ç”¨' },
  çˆ±: { type: 'é™ªä¼´åž‹', purpose: 'æ‹‰è¿‘è·ç¦»ã€ç¤¾ç¾¤ç»´æŠ¤', advice: 'å¤šå›žåº”ã€å¤šåˆ†äº«å¹•åŽï¼Œè®©ç”¨æˆ·æ„Ÿåˆ°è¢«æŽ¥ä½', frequency: 'æ¯å‘¨ 1 æ¡' },
  æ¶: { type: 'ç­›é€‰åž‹', purpose: 'å»ºç«‹é«˜ç«¯æ„Ÿã€ç­›é€‰å®¢æˆ·', advice: 'è¯´æ¸…æ¥šä¸æœåŠ¡è°ï¼Œå»ºç«‹è¾¹ç•Œä¸Žä¸“ä¸šæ„Ÿ', frequency: 'å‘å”®å‰é›†ä¸­ç”¨' },
  æ¬²: { type: 'å‘å¾€åž‹', purpose: 'åˆ¶é€ æ¸´æœ›ã€å“ç‰Œç‰‡', advice: 'å±•ç¤ºç†æƒ³ç»“æžœï¼Œè®©ç”¨æˆ·çœ‹è§æƒ³æˆä¸ºçš„è‡ªå·±', frequency: 'æ¯æœˆ 1 æ¡' }
};

const questions = [
  ['è¡Œä¸šä¸Žäº§å“', 'ä½ çš„è¡Œä¸šèµ›é“æ˜¯ï¼Ÿ', [['ç¾Žä¸š / æŠ¤è‚¤ / ç©¿æ­ / åŒ»ç¾Ž', 'å–œ+2ï¼Œæ¬²+1ï¼Œçˆ±+1'], ['å¤§å¥åº· / å…»ç”Ÿ / è¥å…» / ä¸­åŒ»', 'å–œ+1ï¼Œçˆ±+1ï¼Œæƒ§+1'], ['ç–—æ„ˆ / å¿ƒç†å’¨è¯¢ / èº«å¿ƒçµ', 'çˆ±+2ï¼Œå“€+1ï¼Œå–œ+1'], ['æ•™è‚² / æ•™åŸ¹ / å­¦ç§‘è¾…å¯¼', 'æƒ§+2ï¼Œå–œ+1ï¼Œæ€’+1'], ['å¿ƒç†å­¦ / æƒ…æ„Ÿå’¨è¯¢ / å©šå§»ä¿®å¤', 'çˆ±+2ï¼Œå“€+2'], ['å¾‹å¸ˆ / æ³•å¾‹å’¨è¯¢', 'æƒ§+1ï¼Œæ¶+1ï¼Œæ€’+1'], ['ä¿é™© / ç†è´¢ / è´¢å¯Œç®¡ç†', 'æƒ§+2ï¼Œå–œ+1ï¼Œæ¶+1'], ['å·¥åŽ‚è€æ¿ / å®žä½“è€æ¿ / ä¼ ç»Ÿä¼ä¸šä¸»', 'æ€’+1ï¼Œæ¶+1ï¼Œå–œ+1'], ['IPçŸ¥è¯†ä»˜è´¹æ•™å­¦ / æ“ç›˜æ‰‹ / è‡ªåª’ä½“æ•™ç»ƒ', 'æ€’+2ï¼Œæ¶+1ï¼Œå–œ+1'], ['å…¶ä»–è¡Œä¸š', 'æ ¹æ®äº§å“åˆ¤æ–­']], 'multi', 2],
  ['è¡Œä¸šä¸Žäº§å“', 'ä½ çš„æ ¸å¿ƒäº§å“ä¸»è¦å¸®ç”¨æˆ·è§£å†³ä»€ä¹ˆï¼Ÿ', [['å¸®äººèµšé’± / æå‡æ”¶å…¥', 'æ€’+2ï¼Œæ¶+1ï¼Œå–œ+1'], ['å¸®äººå˜ç¾Ž / å˜å¥½ / å˜å¥åº·', 'å–œ+2ï¼Œæ¬²+1ï¼Œçˆ±+1'], ['å¸®äººå®‰å¿ƒ / ç¼“è§£ç„¦è™‘ / ç–—æ„ˆ', 'çˆ±+2ï¼Œå“€+1'], ['å¸®äººçœæ—¶é—´ / é¿å‘ / å°‘èµ°å¼¯è·¯', 'æƒ§+1ï¼Œæ€’+1ï¼Œæ¶+1']], 'multi', 2],
  ['è¡Œä¸šä¸Žäº§å“', 'ä½ çš„å®¢å•ä»·å±žäºŽï¼Ÿ', [['1â€“5000 å…ƒ', 'çˆ±+2ï¼Œå“€+1ï¼Œæƒ§+1'], ['5000â€“1 ä¸‡', 'å–œ+1ï¼Œæ¬²+1ï¼Œçˆ±+1'], ['1 ä¸‡â€“5 ä¸‡', 'æ¶+2ï¼Œæ€’+1ï¼Œå–œ+1'], ['5 ä¸‡â€“10 ä¸‡', 'æ¶+2ï¼Œæ€’+2'], ['10 ä¸‡ä»¥ä¸Š', 'æ¶+2ï¼Œæ€’+2ï¼Œå–œ+1']], 'multi', 2],
  ['è¡Œä¸šä¸Žäº§å“', 'ä½ çš„äº¤ä»˜æ–¹å¼æ˜¯ï¼Ÿ', [['ä¸€å¯¹ä¸€æ·±åº¦æœåŠ¡ï¼ˆé™ªè·‘ / ç§æ•™ / å’¨è¯¢ï¼‰', 'æ¶+1ï¼Œçˆ±+1ï¼Œå–œ+1'], ['ä¸€å¯¹å¤šè¯¾ç¨‹ / è®­ç»ƒè¥', 'æƒ§+1ï¼Œå–œ+1ï¼Œæ€’+1'], ['ç¤¾ç¾¤ / ä¼šå‘˜åˆ¶é™ªä¼´', 'çˆ±+2ï¼Œå“€+1'], ['å†…å®¹ / å·¥å…· / æ¨¡æ¿ç±»äº§å“', 'å–œ+1ï¼Œæ¬²+1ï¼Œæƒ§+1']], 'multi', 2],
  ['ç”¨æˆ·å¿ƒç†', 'ä½ çš„ç”¨æˆ·æœ€æ€•å¤±åŽ»ä»€ä¹ˆï¼Ÿ', [['æ€•å¤±åŽ»é’± / æœºä¼š', 'æƒ§+2'], ['æ€•è¢«äººè¯„åˆ¤ / ä¸è¢«æŽ¥çº³', 'çˆ±+1ï¼Œå“€+2'], ['æ€•èµ°å¼¯è·¯ / è¢«å‰²éŸ­èœ', 'æ€’+2ï¼Œæ¶+1'], ['æ€•å¹³åº¸ / æ²¡ç»“æžœ', 'å–œ+1ï¼Œæ¬²+2']], 'multi', 2],
  ['ç”¨æˆ·å¿ƒç†', 'ä½ çš„ç”¨æˆ·æœ€æƒ³å¾—åˆ°ä»€ä¹ˆï¼Ÿ', [['æƒ³èµšé’± / æƒ³æˆåŠŸ', 'æ€’+1ï¼Œå–œ+2ï¼Œæ¬²+1'], ['æƒ³å˜ç¾Ž / å˜è‡ªä¿¡', 'å–œ+2ï¼Œæ¬²+2'], ['æƒ³å®‰å¿ƒ / æƒ³è¢«ç†è§£', 'çˆ±+2ï¼Œå“€+1'], ['æƒ³å°‘èµ°å¼¯è·¯ / æƒ³æœ‰äººå¸¦', 'æƒ§+1ï¼Œæ¶+1ï¼Œå–œ+1']], 'multi', 2],
  ['ç”¨æˆ·å¿ƒç†', 'ä½ çš„ç”¨æˆ·å†³å®šä»˜è´¹æ—¶ï¼Œæœ€å¤§çš„éšœç¢æ˜¯ä»€ä¹ˆï¼Ÿ', [['æ€•èŠ±é’±æ²¡æ•ˆæžœ', 'æƒ§+2'], ['æ€•è‡ªå·±åšæŒä¸ä¸‹æ¥', 'æƒ§+1ï¼Œå“€+1'], ['æ€•é‡åˆ°ä¸é è°±çš„äºº', 'æ€’+2ï¼Œæ¶+1'], ['æ€•çŽ°åœ¨ä¸æ˜¯æœ€å¥½æ—¶æœº', 'æƒ§+1ï¼Œæ¬²+1'], ['è§‰å¾—ä»·æ ¼å¤ªé«˜', 'æ¶+1ï¼Œå–œ+1'], ['æ€•èº«è¾¹äººç¬‘è¯', 'çˆ±+2ï¼Œå“€+1'], ['ä¸çŸ¥é“è¯¥é€‰è°', 'æ¶+2ï¼Œæ€’+1'], ['ä¹‹å‰ä¹°è¿‡ç±»ä¼¼çš„æ²¡æ•ˆæžœ', 'æ€’+2ï¼Œå“€+1'], ['æ€•é”™è¿‡æœºä¼š', 'æ¬²+2ï¼Œæƒ§+1'], ['å…¶ä»–éšœç¢', 'æ ¹æ®æƒ…å†µåˆ¤æ–­']], 'multi', 3],
  ['ä¸ªäººç‰¹è´¨', 'ä½ å¹³æ—¶çš„è¯´è¯é£Žæ ¼æ˜¯ï¼Ÿ', [['è¯­é€Ÿå¿«ã€çŠ€åˆ©ã€ä¸€é’ˆè§è¡€', 'æ€’+2ï¼Œæ¶+1'], ['è¯­é€Ÿæ…¢ã€æ¸©æŸ”ã€å¨“å¨“é“æ¥', 'çˆ±+2ï¼Œå“€+1'], ['è½»å¿«ã€å¹½é»˜ã€æœ‰æ„ŸæŸ“åŠ›', 'å–œ+2ï¼Œæ¬²+1'], ['æ²‰ç¨³ã€æƒå¨ã€é€»è¾‘ä¸¥å¯†', 'æƒ§+1ï¼Œæ¶+1ï¼Œå–œ+1']], 'multi', 2],
  ['ä¸ªäººç‰¹è´¨', 'ä½ ç”Ÿæ°”çš„æ—¶å€™é€šå¸¸ä¼šï¼Ÿ', [['ç›´æŽ¥è¡¨è¾¾ï¼Œä¸æ€•å†²çª', 'æ€’+2ï¼Œæ¶+1'], ['å¿ç€ä¸è¯´ï¼Œè‡ªå·±æ¶ˆåŒ–', 'å“€+2ï¼Œçˆ±+1'], ['ç”¨å¹½é»˜åŒ–è§£', 'å–œ+1ï¼Œæ¬²+1'], ['å†·é™åˆ†æžï¼Œè®²é“ç†', 'æƒ§+1ï¼Œæ¶+1']], 'single', 1],
  ['ä¸ªäººç‰¹è´¨', 'ä½ è®²è‡ªå·±ç»åŽ†æ—¶ï¼Œæ›´åå‘ï¼Ÿ', [['å¹³é™å™è¿°ï¼Œåƒè®²æ•…äº‹', 'å“€+2ï¼Œçˆ±+1'], ['æœ‰æƒ…ç»ªèµ·ä¼ï¼Œåƒæ¼”è®²', 'æ€’+1ï¼Œå–œ+1ï¼Œæ¬²+1'], ['è½»ææ·¡å†™ï¼Œä¸æ¸²æŸ“', 'æ¶+1ï¼Œå–œ+1'], ['é€»è¾‘æ¸…æ™°ï¼Œåƒä¸Šè¯¾', 'æƒ§+1ï¼Œæ¶+1']], 'multi', 2],
  ['ä¸ªäººç‰¹è´¨', 'ä½ çš„é•¿ç›¸ / æ°”è´¨æ›´æŽ¥è¿‘ï¼Ÿ', [['æ°”åœºå¼ºã€å¹²ç»ƒã€æœ‰è·ç¦»æ„Ÿ', 'æ¶+2ï¼Œæ€’+1'], ['äº²å’Œã€æ¸©æš–ã€é‚»å®¶æ„Ÿ', 'çˆ±+2ï¼Œå“€+1'], ['é˜³å…‰ã€æ´»åŠ›ã€æœ‰èƒ½é‡', 'å–œ+2ï¼Œæ¬²+1'], ['çŸ¥æ€§ã€ä¸“ä¸šã€å¯ä¿¡èµ–', 'æƒ§+1ï¼Œå–œ+1']], 'multi', 2],
  ['ä¸ªäººç‰¹è´¨', 'ä½ é¢å¯¹é•œå¤´æ—¶ï¼Œæœ€è‡ªç„¶çš„çŠ¶æ€æ˜¯ï¼Ÿ', [['ç›´æŽ¥å¼€æ€¼ï¼Œæ•¢è¯´çœŸè¯', 'æ€’+2ï¼Œæ¶+1'], ['æ¸©æŸ”åˆ†äº«ï¼Œåƒè·Ÿæœ‹å‹èŠå¤©', 'çˆ±+2ï¼Œå“€+1'], ['è‡ªä¿¡å±•ç¤ºï¼Œæ™’ç»“æžœ', 'å–œ+2ï¼Œæ¬²+1'], ['ä¸¥è‚ƒåˆ†æžï¼Œç»™å¹²è´§', 'æƒ§+1ï¼Œæ¶+1']], 'multi', 2],
  ['ä¸ªäººç‰¹è´¨', 'ä½ æ›´å–œæ¬¢å“ªç§è¡¨è¾¾æ–¹å¼ï¼Ÿ', [['è®²è§‚ç‚¹ã€äº®æ€åº¦', 'æ€’+2ï¼Œæ¶+1'], ['è®²æ•…äº‹ã€è®²ç»åŽ†', 'å“€+2ï¼Œçˆ±+1'], ['è®²ç»“æžœã€è®²æ¡ˆä¾‹', 'å–œ+2ï¼Œæ¬²+1'], ['è®²æ–¹æ³•ã€è®²é€»è¾‘', 'æƒ§+1ï¼Œæ¶+1']], 'multi', 2],
  ['å…«å­—äº”è¡Œ Â· å¯é€‰', 'ä½ çš„æ—¥ä¸»äº”è¡Œæ˜¯ï¼Ÿ', [['ç«ï¼ˆä¸™ã€ä¸ï¼‰', 'æ€’+2ï¼Œå–œ+1'], ['åœŸï¼ˆæˆŠã€å·±ï¼‰', 'æ¶+1ï¼Œå–œ+1'], ['æœ¨ï¼ˆç”²ã€ä¹™ï¼‰', 'æ€’+1ï¼Œæ¬²+1'], ['æ°´ï¼ˆå£¬ã€ç™¸ï¼‰', 'å“€+1ï¼Œçˆ±+1'], ['é‡‘ï¼ˆåºšã€è¾›ï¼‰', 'æƒ§+1ï¼Œæ¶+1']], 'single', 1],
  ['å…«å­—äº”è¡Œ Â· å¯é€‰', 'ä½ çš„å…«å­—èº«å¼ºè¿˜æ˜¯èº«å¼±ï¼Ÿ', [['èº«å¼º', 'æ€’+1ï¼Œå–œ+1ï¼Œæ¶+1'], ['èº«å¼±', 'å“€+1ï¼Œçˆ±+1ï¼Œæƒ§+1']], 'single', 1]
];

let current = 0;
let answers = Array.from({ length: questions.length }, () => []);
const scores = () => Object.fromEntries(Object.keys(emotions).map(key => [key, 0]));
const $ = id => document.getElementById(id);
const scoreFromText = text => { const result = {}; [...text.matchAll(/([æ€’å–œå“€æƒ§çˆ±æ¶æ¬²])\+(\d)/g)].forEach(match => { result[match[1]] = Number(match[2]); }); return result; };

function show(id) { ['introView', 'quizView', 'resultView'].forEach(view => $(view).classList.toggle('hidden', view !== id)); }
function showToast(message) { const toast = $('toast'); toast.textContent = message; toast.classList.add('visible'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('visible'), 2400); }
function makeShareUrl(includeAnswers = false) { const url = new URL(window.location.href); url.hash = ''; if (includeAnswers) url.searchParams.set('answers', answers.map(selection => selection.length ? selection.reduce((mask, index) => mask | (1 << index), 0) : 'x').join('.')); return url.toString(); }
async function shareUrl(url, message) { try { if (navigator.share) { await navigator.share({ title: 'åˆ›å§‹äºº IP æƒ…ç»ªé£Žæ ¼æµ‹è¯„', text: message, url }); } else { await navigator.clipboard.writeText(url); showToast('åˆ†äº«é“¾æŽ¥å·²å¤åˆ¶ï¼Œå‘ç»™å­¦å‘˜å³å¯'); } } catch (error) { if (error.name !== 'AbortError') { try { await navigator.clipboard.writeText(url); showToast('åˆ†äº«é“¾æŽ¥å·²å¤åˆ¶'); } catch (clipboardError) { showToast('è¯·å¤åˆ¶æµè§ˆå™¨åœ°å€æ é“¾æŽ¥åˆ†äº«'); } } } }
function openShareModal() { const url = makeShareUrl(); $('shareUrlInput').value = url; $('shareQrImage').src = `https://quickchart.io/qr?size=260&margin=2&text=${encodeURIComponent(url)}`; $('shareModal').classList.remove('hidden'); document.body.classList.add('modal-open'); }
function closeShareModal() { $('shareModal').classList.add('hidden'); document.body.classList.remove('modal-open'); }
async function copyShareUrl() { const url = $('shareUrlInput').value; try { await navigator.clipboard.writeText(url); } catch (error) { $('shareUrlInput').select(); document.execCommand('copy'); } showToast('æµ‹è¯„ç½‘å€å·²å¤åˆ¶'); }
function downloadQr() { const link = document.createElement('a'); link.download = 'åˆ›å§‹äººIPæƒ…ç»ªé£Žæ ¼æµ‹è¯„äºŒç»´ç .png'; link.href = $('shareQrImage').src; link.target = '_blank'; link.click(); }
function loadSharedResult() { const encoded = new URLSearchParams(window.location.search).get('answers'); if (!encoded || !/^[0-9x]+(?:\.[0-9x]+)*$/.test(encoded)) return false; const tokens = encoded.includes('.') ? encoded.split('.') : [...encoded]; if (tokens.length !== questions.length) return false; if (tokens.some((token, index) => token !== 'x' && Number(token) > (1 << questions[index][2].length) - 1)) return false; answers = tokens.map((token, index) => { if (token === 'x') return []; const mask = Number(token); return Array.from({ length: questions[index][2].length }, (_, optionIndex) => optionIndex).filter(optionIndex => mask & (1 << optionIndex)); }); renderResults(); show('resultView'); $('headerStatus').textContent = 'å·²æ‰“å¼€åˆ†äº«ç»“æžœ'; return true; }
function renderQuestion() {
  const [section, title, options, mode, maxSelection] = questions[current];
  $('sectionLabel').textContent = `${current < 4 ? 'ç¬¬ä¸€éƒ¨åˆ†' : current < 7 ? 'ç¬¬äºŒéƒ¨åˆ†' : current < 13 ? 'ç¬¬ä¸‰éƒ¨åˆ†' : 'ç¬¬å››éƒ¨åˆ†'} Â· ${section}`;
  $('questionTitle').textContent = title; $('currentNumber').textContent = String(current + 1).padStart(2, '0'); $('progressBar').style.width = `${((current + 1) / questions.length) * 100}%`; $('skipHint').textContent = mode === 'single' ? 'å•é€‰é¢˜ Â· è¯·é€‰æ‹©æœ€ç¬¦åˆçš„ä¸€é¡¹' : `å¤šé€‰é¢˜ Â· æœ€å¤šé€‰æ‹© ${maxSelection} é¡¹`;
  $('options').innerHTML = options.map((option, index) => `<div class="option ${answers[current].includes(index) ? 'selected' : ''}" data-index="${index}"><span class="option-letter">${answers[current].includes(index) ? 'âœ“' : String.fromCharCode(65 + index)}</span><div class="option-copy"><strong>${option[0]}</strong><small>${option[1] || 'æœ¬é¢˜ä¸è®¡åˆ†'}</small></div></div>`).join('');
  document.querySelectorAll('.option').forEach(option => option.addEventListener('click', () => { const index = Number(option.dataset.index); const selected = answers[current]; if (selected.includes(index)) answers[current] = selected.filter(item => item !== index); else if (mode === 'single') answers[current] = [index]; else if (selected.length < maxSelection) answers[current] = [...selected, index]; else { showToast(`æœ¬é¢˜æœ€å¤šé€‰æ‹© ${maxSelection} é¡¹`); return; } renderQuestion(); }));
  $('prevButton').disabled = current === 0; $('nextButton').disabled = answers[current].length === 0; $('nextButton').innerHTML = current === questions.length - 1 ? 'æŸ¥çœ‹ç»“æžœ <span>â†—</span>' : 'ä¸‹ä¸€é¢˜ <span>â†’</span>';
}
function calculate() { const total = scores(); answers.forEach((selection, questionIndex) => selection.forEach(answer => Object.entries(scoreFromText(questions[questionIndex][2][answer][1])).forEach(([emotion, value]) => { total[emotion] += value; }))); return Object.entries(total).sort((a, b) => b[1] - a[1]); }
function renderResults() {
  const ranked = calculate(); const primary = ranked[0][0]; const support = ranked.slice(1, 3).map(item => item[0]); const avoid = ranked.slice(-2).map(item => item[0]); const max = ranked[0][1] || 1;
  $('dominantEmotion').textContent = primary; $('dominantType').textContent = emotions[primary].type; $('dominantSummary').textContent = `${emotions[primary].advice}ã€‚ä½ çš„å†…å®¹é¦–å…ˆè¦è®©ç”¨æˆ·æ„Ÿå—åˆ°${emotions[primary].purpose.replace('å»ºç«‹äººè®¾ã€', '').replace('ã€æ›¿ç”¨æˆ·è¯´è¯', '')}ã€‚`; $('dominantScore').textContent = `å¾—åˆ† ${ranked[0][1]}`; $('dominantFrequency').textContent = emotions[primary].frequency;
  $('resultTitle').textContent = `${primary} Ã— ${support.join(' Ã— ')} é…æ–¹`; $('resultSubtitle').textContent = `${emotions[primary].type}ä¸ºä¸»ï¼Œ${emotions[support[0]].type}ä¸Ž${emotions[support[1]].type}è¾…åŠ©`;
  $('scoreBars').innerHTML = ranked.map(([emotion, score]) => `<div class="score-bar-row"><strong>${emotion}</strong><div class="score-bar-track"><div class="score-bar-fill" style="width:${Math.max(5, score / max * 100)}%"></div></div><span>${score}</span></div>`).join('');
  $('primaryEmotion').textContent = `${primary} Â· ${emotions[primary].type}`; $('supportEmotions').textContent = support.map(emotion => `${emotion} Â· ${emotions[emotion].type}`).join(' + '); $('contentRatio').textContent = '60% + 25% + 15%';
  $('contentAdvice').innerHTML = [primary, ...support].map((emotion, index) => `<div class="advice-item"><strong>${[60, 25, 15][index]}% ${emotion} Â· ${emotions[emotion].type}</strong><span>${emotions[emotion].advice}ã€‚${emotions[emotion].purpose}ï¼Œå»ºè®®${emotions[emotion].frequency}ã€‚</span></div>`).join(''); $('avoidAdvice').textContent = `${avoid.join('ã€')}ï¼šåˆ†æ•°è¾ƒä½Žï¼Œæš‚æ—¶ä¸è¦æŠŠå®ƒä»¬å½“ä½œä¸»è¦è¡¨è¾¾ã€‚ä½ çš„å†…å®¹æ›´é€‚åˆä»Žã€Œ${emotions[primary].type}ã€å‡ºå‘ï¼Œä¿æŒçœŸå®žæ¯”åˆ»æ„è¡¥é½æ‰€æœ‰æƒ…ç»ªæ›´é‡è¦ã€‚`; $('completionCopy').textContent = `å®Œæˆåº¦ ${Math.round(answers.filter(selection => selection.length).length / questions.length * 100)}%`; $('signalCopy').textContent = ranked[0][1] - ranked[1][1] >= 3 ? 'æƒ…ç»ªä¿¡å·æ¸…æ™°' : 'æƒ…ç»ªç»„åˆä¸°å¯Œ'; $('emotionTags').innerHTML = ranked.slice(0, 4).map(([emotion, score], index) => `<span class="emotion-tag tag-${index}">${emotion} Â· ${emotions[emotion].type}<b>${score}</b></span>`).join('');
  const profile = [['è¡Œä¸šèµ›é“', answerText(0)], ['æ ¸å¿ƒäº§å“', answerText(1)], ['å®¢å•ä»·', answerText(2)], ['äº¤ä»˜æ–¹å¼', answerText(3)], ['ç”¨æˆ·æœ€æ€•', answerText(4)], ['ç”¨æˆ·æœ€æƒ³è¦', answerText(5)], ['ç”¨æˆ·å†³ç­–éšœç¢', answerText(6)], ['è¯´è¯é£Žæ ¼', answerText(7)], ['ç”Ÿæ°”æ—¶ååº”', answerText(8)], ['è®²ç»åŽ†æ–¹å¼', answerText(9)], ['æ°”è´¨ç±»åž‹', answerText(10)], ['é¢å¯¹é•œå¤´çŠ¶æ€', answerText(11)], ['è¡¨è¾¾æ–¹å¼åå¥½', answerText(12)], ['ä¸»æƒ…ç»ª', `${primary} Â· ${emotions[primary].type}`], ['è¾…åŠ©æƒ…ç»ª 1', `${support[0]} Â· ${emotions[support[0]].type}`], ['è¾…åŠ©æƒ…ç»ª 2', `${support[1]} Â· ${emotions[support[1]].type}`], ['é¿å¼€æƒ…ç»ª', avoid.join('ã€')], ['ä¸»æŽ¨è§†é¢‘ç±»åž‹', emotions[primary].type], ['å†…å®¹é…æ¯”', `${primary} 60% + ${support[0]} 25% + ${support[1]} 15%`]];
  $('profileGrid').innerHTML = profile.map((item, index) => `<div class="profile-item ${index === 12 ? 'wide' : ''}"><span>${item[0]}</span><strong>${item[1]}</strong></div>`).join(''); $('headerStatus').textContent = 'æµ‹è¯„å·²å®Œæˆ';
}
function answerText(index) { const selection = answers[index]; return selection.length ? selection.map(answer => questions[index][2][answer][0]).join('ã€') : 'æœªå¡«å†™'; }
function ensureResultLayout() { const description = document.querySelector('.intro-description'); const note = document.querySelector('.micro-note'); if (description) description.textContent = 'ç”¨æƒ…ç»ªè¡¨è¾¾åšçˆ†æ¬¾ï¼Œç”¨ä¿¡ä»»è¡¨è¾¾åšæˆäº¤ã€‚10 åˆ†é’Ÿæ‰¾åˆ°å±žäºŽä½ çš„æƒ…ç»ªé…æ–¹ã€å†…å®¹æ¯”ä¾‹å’Œå¯ç›´æŽ¥æ‰§è¡Œçš„è§†é¢‘æ–¹å‘ã€‚'; if (note) note.textContent = '15 é¢˜ Â· çº¦ 10 åˆ†é’Ÿ Â· å•é€‰ä¸Žå¤šé€‰'; if (!$('dominantResult') && $('resultCard')) $('resultCard').insertAdjacentHTML('beforebegin', '<div id="dominantResult" class="dominant-result"><div class="dominant-orb"><span id="dominantEmotion">æ€’</span><small>ä¸»æƒ…ç»ª</small></div><div class="dominant-copy"><p class="eyebrow">YOUR DOMINANT SIGNAL</p><h3><strong id="dominantType">ç«‹åœºåž‹</strong>äººæ ¼</h3><p id="dominantSummary">ä½ æœ€é€‚åˆç”¨æ¸…æ™°çš„ç«‹åœºå’Œè¾¹ç•Œï¼Œè®©ç”¨æˆ·è¿…é€Ÿè®°ä½ä½ ã€‚</p><div class="dominant-meta"><span id="dominantScore">å¾—åˆ† 0</span><span id="dominantFrequency">æ¯å‘¨ 1â€“2 æ¡</span></div></div><div class="dominant-badge">TOP<br><strong>01</strong></div></div>'); }
function downloadResult() { const canvas = document.createElement('canvas'); canvas.width = 1200; canvas.height = 760; const context = canvas.getContext('2d'); context.fillStyle = '#202320'; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#d8ef72'; context.fillRect(70, 72, 95, 10); context.fillStyle = '#f4f1ea'; context.font = '700 24px sans-serif'; context.fillText('FOUNDER IP PROFILE', 70, 145); context.font = '600 58px serif'; context.fillText($('resultTitle').textContent, 70, 215); context.fillStyle = '#aeb3a9'; context.font = '20px sans-serif'; context.fillText($('resultSubtitle').textContent, 70, 255); const rows = [...document.querySelectorAll('.score-bar-row')]; rows.forEach((row, index) => { const y = 335 + index * 38; context.fillStyle = '#f4f1ea'; context.font = '700 18px sans-serif'; context.fillText(row.children[0].textContent, 75, y); context.fillStyle = '#424940'; context.fillRect(125, y - 14, 700, 11); context.fillStyle = '#d8ef72'; context.fillRect(125, y - 14, 700 * parseFloat(row.children[1].firstElementChild.style.width) / 100, 11); context.fillStyle = '#aeb3a9'; context.font = '16px sans-serif'; context.fillText(row.children[2].textContent, 850, y); }); context.fillStyle = '#ff795f'; context.font = '700 22px sans-serif'; context.fillText('å†…å®¹é…æ¯”  60% + 25% + 15%', 70, 680); context.fillStyle = '#aeb3a9'; context.font = '16px sans-serif'; context.fillText('åˆ›å§‹äºº IP æƒ…ç»ªé£Žæ ¼æµ‹è¯„ Â· ä¿å­˜äºŽä½ çš„å†…å®¹æ¡£æ¡ˆ', 70, 720); const link = document.createElement('a'); link.download = 'åˆ›å§‹äººIPæƒ…ç»ªé£Žæ ¼æµ‹è¯„ç»“æžœ.png'; link.href = canvas.toDataURL('image/png'); link.click(); }

function downloadResult() {
  const canvas = document.createElement('canvas'); canvas.width = 1400; canvas.height = 1780; const context = canvas.getContext('2d'); const ranked = calculate(); const primary = ranked[0][0];
  const rounded = (x, y, width, height, radius, fill, stroke) => { context.beginPath(); context.roundRect(x, y, width, height, radius); context.fillStyle = fill; context.fill(); if (stroke) { context.strokeStyle = stroke; context.stroke(); } };
  const wrapped = (text, x, y, width, lineHeight, color, font) => { context.fillStyle = color; context.font = font; let line = ''; let cursorY = y; [...text].forEach(character => { const next = line + character; if (context.measureText(next).width > width && line) { context.fillText(line, x, cursorY); line = character; cursorY += lineHeight; } else line = next; }); if (line) context.fillText(line, x, cursorY); return cursorY; };
  context.fillStyle = '#f6f1fb'; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#e7d7ff'; context.fillRect(0, 0, canvas.width, 290); context.fillStyle = '#6d43d9'; context.fillRect(82, 75, 118, 12); context.fillStyle = '#211b32'; context.font = '700 24px sans-serif'; context.fillText('FOUNDER IP / EMOTIONAL POSITIONING', 82, 135); context.font = '600 58px serif'; context.fillText('åˆ›å§‹äºº IP æƒ…ç»ªé£Žæ ¼æŠ¥å‘Š', 82, 210); context.fillStyle = '#777083'; context.font = '20px sans-serif'; context.fillText('ç”¨æƒ…ç»ªè¡¨è¾¾åšçˆ†æ¬¾ï¼Œç”¨ä¿¡ä»»è¡¨è¾¾åšæˆäº¤ã€‚', 84, 252);
  rounded(70, 330, 1260, 310, 28, '#2b1d43'); context.fillStyle = '#d9f47b'; context.font = '700 18px sans-serif'; context.fillText('YOUR DOMINANT SIGNAL Â· TOP 01', 110, 390); context.fillStyle = '#ffffff'; context.font = '600 70px serif'; context.fillText(`${primary}åž‹äººæ ¼`, 110, 480); wrapped(`${emotions[primary].advice}ã€‚ä½ çš„å†…å®¹é¦–å…ˆè¦è®©ç”¨æˆ·æ„Ÿå—åˆ°${emotions[primary].purpose.replace('å»ºç«‹äººè®¾ã€', '').replace('ã€æ›¿ç”¨æˆ·è¯´è¯', '')}ã€‚`, 112, 535, 760, 34, '#ded1ea', '20px sans-serif'); context.fillStyle = '#d9f47b'; context.beginPath(); context.arc(1160, 470, 105, 0, Math.PI * 2); context.fill(); context.fillStyle = '#2b1d43'; context.textAlign = 'center'; context.font = '700 74px serif'; context.fillText(primary, 1160, 490); context.font = '16px sans-serif'; context.fillText(`${emotions[primary].type} Â· å¾—åˆ† ${ranked[0][1]}`, 1160, 530); context.textAlign = 'left';
  context.fillStyle = '#777083'; context.font = '700 16px sans-serif'; context.fillText('ä¸ƒæƒ…ç»ªåˆ†å¸ƒ Â· ä»Žé«˜åˆ°ä½Ž', 82, 705); ranked.forEach(([emotion, score], index) => { const y = 765 + index * 45; context.fillStyle = '#211b32'; context.font = '700 19px sans-serif'; context.fillText(`${String(index + 1).padStart(2, '0')}  ${emotion}`, 90, y); rounded(230, y - 18, 760, 14, 7, '#e1d9eb'); rounded(230, y - 18, Math.max(25, 760 * score / (ranked[0][1] || 1)), 14, 7, index === 0 ? '#6d43d9' : '#b175d8'); context.fillStyle = '#777083'; context.font = '16px sans-serif'; context.fillText(`${score} Â· ${emotions[emotion].type}`, 1030, y); });
  rounded(70, 1135, 600, 270, 22, '#ffffff', '#ded6ea'); rounded(700, 1135, 630, 270, 22, '#ffffff', '#ded6ea'); context.fillStyle = '#6d43d9'; context.font = '700 15px sans-serif'; context.fillText('CONTENT DIRECTION', 105, 1185); context.fillStyle = '#211b32'; context.font = '600 29px serif'; context.fillText('å†…å®¹é…æ¯”', 105, 1235); context.font = '700 22px sans-serif'; context.fillText(`${primary} 60% + ${ranked[1][0]} 25% + ${ranked[2][0]} 15%`, 105, 1290); wrapped(`ä¸»æƒ…ç»ªï¼š${emotions[primary].advice}ã€‚è¾…åŠ©æƒ…ç»ªï¼š${emotions[ranked[1][0]].advice}ã€‚`, 105, 1345, 500, 28, '#777083', '17px sans-serif'); context.fillStyle = '#6d43d9'; context.font = '700 15px sans-serif'; context.fillText('ACTION NOTES', 735, 1185); context.fillStyle = '#211b32'; context.font = '600 29px serif'; context.fillText('ä¸‹ä¸€æ­¥è¿™æ ·æ‹', 735, 1235); wrapped(`ä¸»æŽ¨ç±»åž‹ï¼š${emotions[primary].type}ã€‚${emotions[primary].purpose}ã€‚${emotions[primary].frequency}ã€‚`, 735, 1290, 520, 28, '#777083', '17px sans-serif');
  context.fillStyle = '#777083'; context.font = '700 15px sans-serif'; context.fillText('IP æƒ…ç»ªé£Žæ ¼æ¡£æ¡ˆå¡', 82, 1500); const profileRows = [...document.querySelectorAll('.profile-item')].slice(0, 9); profileRows.forEach((item, index) => { const x = 82 + (index % 3) * 425; const y = 1540 + Math.floor(index / 3) * 62; context.fillStyle = '#777083'; context.font = '13px sans-serif'; context.fillText(item.querySelector('span').textContent, x, y); context.fillStyle = '#211b32'; context.font = '600 16px sans-serif'; context.fillText(item.querySelector('strong').textContent.slice(0, 22), x, y + 26); }); context.fillStyle = '#aaa0b4'; context.font = '14px sans-serif'; context.fillText('åˆ›å§‹äºº IP æƒ…ç»ªé£Žæ ¼æµ‹è¯„ Â· ç»“æžœæŠ¥å‘Š', 82, 1740);
  const link = document.createElement('a'); link.download = 'åˆ›å§‹äººIPæƒ…ç»ªé£Žæ ¼å®Œæ•´ç»“æžœæŠ¥å‘Š.png'; link.href = canvas.toDataURL('image/png'); link.click();
}

ensureResultLayout(); $('startButton').addEventListener('click', () => { current = 0; answers = Array.from({ length: questions.length }, () => []); show('quizView'); $('headerStatus').textContent = 'æ­£åœ¨æµ‹è¯„'; renderQuestion(); }); $('shareTestButton').addEventListener('click', openShareModal); $('shareResultButton').addEventListener('click', () => shareUrl(makeShareUrl(true), 'è¿™æ˜¯æˆ‘çš„åˆ›å§‹äºº IP æƒ…ç»ªé£Žæ ¼ç»“æžœ')); $('closeShareButton').addEventListener('click', closeShareModal); $('copyShareButton').addEventListener('click', copyShareUrl); $('downloadQrButton').addEventListener('click', downloadQr); document.querySelectorAll('[data-close-share]').forEach(element => element.addEventListener('click', closeShareModal)); document.addEventListener('keydown', event => { if (event.key === 'Escape') closeShareModal(); }); $('prevButton').addEventListener('click', () => { if (current > 0) { current--; renderQuestion(); } }); $('nextButton').addEventListener('click', () => { if (current < questions.length - 1) { current++; renderQuestion(); } else { renderResults(); show('resultView'); window.scrollTo({ top: 0, behavior: 'smooth' }); } }); $('restartButton').addEventListener('click', () => { show('introView'); $('headerStatus').textContent = 'å‡†å¤‡å¼€å§‹'; window.history.replaceState({}, '', window.location.pathname); window.scrollTo({ top: 0, behavior: 'smooth' }); }); $('saveImageButton').addEventListener('click', downloadResult); loadSharedResult();
